### ISSUE TITLE
OrderBy( Func<TEntity, object> ) does not expose ToListAsync

### ISSUE THREAD

**Issue by felipedrumond** [aspnet/EntityFramework6#103]
I'm trying to read an ordered list asynchronously passing a **Func<TEntity, object>** to the **OrderByDescending** method. The problem is that calling this method passing this kind of parameter does not expose the ToListAsync that I want to use. Instead, I can pass a **Expression<Func<TEntity, object>>** to that method, which exposes the async method. 

```
public virtual Expression<Func<TEntity, object>>  OrderBy { get; set; }
OrderBy = u => u.Relevance; <- decimal field

public virtual async Task<List<TEntity>> ReadAsync(Expression<Func<TEntity, bool>> criteria)
{
 return await _dbSet.Where(criteria).OrderByDescending(OrderBy).Skip(Skip).ToListAsync();
}
```

This code throws _Unable to cast the type 'System.Decimal' to type 'System.Object'. LINQ to Entities only supports casting EDM primitive or enumeration types._ Why can EF solve **Func<TEntity, object>** but can't it solve **Expression<Func<TEntity, object>>**? If at least the Order methods exposed the async methods, it would be fine.

Is there any solution for this?

**Comment by divega** [comment]
@felipedrumond there are a few parts to the answer:

1. Where the LINQ extension methods for `IEnumerable<T>` take parameters of type `Func<T,...>` the equivalent `IQueryable<T>` extension methods take `Expression<Func<T,...>>` and that is by design. If you use the version that takes a regular `Func<T,...>` you are binding to the `IEnumerable<T>` version of the method which means that (synchronous) enumeration will happen any further LINQ operators you add to the query will be evaluated in memory. 

2. It doesn't make much sense to have async versions of `OrderBy[Descending]()` on `IQueryable<T>`: the method will not trigger execution. The version on `IEnumerable<T>` will trigger synchronous execution because that is the only kind of enumeration `IEnumerable<T>` supports. 

3. The LINQ implementation in EF6 (or previous versions) does not support ordering on expressions of type object, which means that if you call `OrderBy()` or `OrderByDescending()` with an `Expression<Func<TEntity, object>>` it will fail. You will have to use a specific T. So it is a bit harder to write something that will work. 

I will post tomorrow some code that you can use as a starting point.

**Comment by divega** [comment]
@felipedrumond As promised, here is some sample code I put together that you can use to work with `OrderBy()` in such way that you can pick different key expressions at runtime without knowing their types on advance but it will still preserve the type of the key and therefore will work with EF6. 

**Keep in mind that this is just sample code: E.g. I haven't included even the minimal parameter checks so if you use this code in an unintended way you will likely get strange exceptions.**

``` C#
using System;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using Xunit;

namespace UntypedOrderByEF6
{

    public class Test
    {
        [Fact]
        public void TestDynamicOrderBy()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<MyContext>());
            using (var db = new MyContext())
            {
                db.People.Add(new Person { Name = "George", BirthDate = new DateTime(1943, 2, 25) });
                db.People.Add(new Person { Name = "Ringo", BirthDate = new DateTime(1940, 7, 7) });
                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                var sourceQuery = db.People;

                var birthDateKeyExpression = sourceQuery.GetOrderByKey(x => x.BirthDate);
                Assert.Equal(sourceQuery.OrderBy(birthDateKeyExpression).First().Name, "Ringo");

                var idKeyExpression = sourceQuery.GetOrderByKey(x => x.Name);
                Assert.Equal(sourceQuery.OrderBy(idKeyExpression).First().Name, "George");
            }
        }

        public class Person
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public DateTime BirthDate { get; set; }
        }

        public class MyContext : DbContext
        {
            public DbSet<Person> People { get; set; }
        }
    }

    public static class UntypedOrderByExtensions
    {
        private static MethodInfo _orderBy = typeof(Queryable)
            .GetTypeInfo()
            .GetDeclaredMethods(nameof(Queryable.OrderBy))
            .Single(mi => mi.GetParameters().Length == 2);

        public static LambdaExpression GetOrderByKey<TSource, TExpression>(this IQueryable<TSource> source, Expression<Func<TSource, TExpression>> keyExpression)
            => keyExpression;

        public static IOrderedQueryable<TSource> OrderBy<TSource>(this IQueryable<TSource> source, LambdaExpression keyExpression)
            => (IOrderedQueryable<TSource>)source.Provider.CreateQuery<TSource>(
                Expression.Call(
                    null,
                    _orderBy.MakeGenericMethod(keyExpression.Parameters[0].Type, keyExpression.ReturnType),
                    source.Expression, Expression.Quote(keyExpression)
                    ));
    }
}
```

**Comment by felipedrumond** [comment]
Thank you very much @divega. This probably will help me to get rid of my workaround (putting the whole list in cache after reading from database to avoid running an order by NewID() ).
Thank you!
