### ISSUE TITLE
varchar Foreign Key comparison is case-sensitive, ignoring the case-sensitivity collation setting of the database

### ISSUE THREAD

**Issue by eddieloeffen** [aspnet/EntityFramework6#108]
This issue has been on Stack Overflow for a number of years but I could not find an actual GitHub issue recorded for it:

http://stackoverflow.com/questions/9751647/entity-framework-nvarchar-case-sensitivity-on-foreign-key
http://stackoverflow.com/questions/32224102/entity-framework-varchar-foreign-key-case-insensitive

**Comment by divega** [comment]
Related:

- EF6 issue form CodePlex: https://entityframework.codeplex.com/workitem/284 (10 votes)
- EF Core backlog issue: https://github.com/aspnet/EntityFramework/issues/673.

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to implement in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue... we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.
![image](https://cloud.githubusercontent.com/assets/4741851/20680727/1c8af070-b555-11e6-9fb7-87682e9df3e8.png)
