### ISSUE TITLE
Table Per Type Inheritance -- extending an existing type

### ISSUE THREAD

**Issue by jemartin80** [aspnet/EntityFramework6#120]
Table per type is a commonly used database design pattern, but the ability to extend a base table into an extended table is currently lacking. An example. 

**Data design** 

    People 
        ID     PK
        Name
    Student
        ID     PK    FK People(ID)
        Major
**Classes**
    
    class Person { ID, Name }
    class Student : Person { Major }

The problem is if I have an existing Person and this person becomes a Student, there is no clean way to do this in EF6. I have to resort to ExecuteSQLCommand. Craig Stuntz makes an excellent philosophical point for why this limitation should exist on stack overflow http://stackoverflow.com/a/1364248. But this doesn't change the fact that there is strong use case for this functionality. I could expound upon why TPC and TPH are much weaker design patterns than TPT in my situation and in many other generalized situations, but I imagine this is already recognized to be true. Elegance and philosophy are critical in any library, but they shouldn't be substituted from practical usability.

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
To add a little more specific info... EF is built on the assumption that entities do not change type. Changing this assumption would be a very significant undertaking with wide reaching implications. 

Performing the change directly in the database, using a raw SQL command, and then loading the data in a new context instance is the best way to perform this operation with EF6.x.

**Comment by pravinkarthy** [comment]
@rowanmiller Is there a better way to handle this inheritance scenario with TPH in EFCore 2.2 ?

People (Base Type)
    ID   -  PK
    Name

Student : People
    ID   -  PK ,   FK People(ID)
    Major
