### ISSUE TITLE
Entity has four key properties used in multiple relationships ... how does relationship specify when keys to use?

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#121]
See #114 that is closed. "I have an Oracle DB and would like to create an entity. The entity is on the 1 side of multiple 1-to-many relationships. E.g. I would like Relationship A to use 1 and 3 and Relationship B to 2, 3 & 4."

I have found no way to specify in a relationship specified via fluent API which properties on the one side are the targets of the foreign keys specified for the many side. Is this a capability enabled only in a recent EF release?

Daniel

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
This feature is known as Alternate Keys, and is implemented in EF Core, but is not something we are going to add to EF6.x.
