### ISSUE TITLE
Migration code generation

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1256]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/729941/migration-code-generation.html)._

---
I am using migrations to create my tables in my database.  I ran a migration yesterday to create a table.  Today I decided to rename the table, add a few columns and delete a few columns.  The Up() method that was generated gave me the following code along with other code to implement my changes:

RenameTable(name: &quot;StandardSilo.StandardSiloPartArchived&quot;, newName: &quot;StandardSiloPartLogs&quot;);
DropForeignKey(&quot;StandardSilo.StandardSiloPartArchived&quot;, &quot;SegmentNumberId&quot;, &quot;dbo. SegmentNumbers&quot;);

This caused an error because you can't rename  a table, and then try to drop a foreignkey using the old name.  It was a simple fix to simply switch the lines, but took a bit of time to realize what was going on.

---
#### Visual Studio Feedback System on 9/11/2019, 04:05 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
