### ISSUE TITLE
HasKey and runtime created anon type for key

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#131]
I have an application where I need to define entity types at runtime.

I have code running that creates entity types and I can build models derived from DbContext etc. and it all works to retrieve data from an Oracle database as long as I have non-composite keys. 

I use reflection to create the equivalent of this in my OnMOdelCreating()
   modelBuilder.Entity<myRuntimeEntityType>()
      .HasKey(e => e.property);

The defintion of .HasKey is
   public EntityTypeConfiguration<TEntityType> HasKey<TKey>(
      Expression<Func<TEntityType, TKey>> keyExpression)

My code work fine for non-composite keys since I know the type of e.property and can use it to create the appropriate .HasKey<TKey> at runtime and then invoke it with a dynamic lambda expression I have created.

I would like to use reflection to create the equivalent of this composite key:
   modelBuilder.Entity<myRuntimeEntityType>()
      .HasKey(e => new { e.stringProperty, e.datetimeProperty});

So in the composite case TKey is
   anon {System.String. System.DateTime}

If I can find a way to use reflection to create the TKey for the anonymous type and build the appropriate lambda expression, will EF allow me to do this since my anonymous type TKey is transient and only exists while I am in OnModelCreating()?

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
cc @anpete who has an idea for a workaround
