### ISSUE TITLE
Problem Generating Entity Model From Database

### ISSUE THREAD

**Issue by oidocrop2019** [aspnet/EntityFramework6#1397]
I have a database with four tables in sql server generated with code first. When i try to use the database in an other project and import the model, the table customer does not appear.

```
Not exception is thrown
```

### Steps to reproduce
this is the database code in sql server
[Database.zip](https://github.com/aspnet/EntityFramework6/files/3742965/Database.zip)

These are the steps used to import the database

![EfDesigner](https://user-images.githubusercontent.com/56717659/67078603-e5d4ef00-f191-11e9-9f15-1e66a6c28f23.PNG)

In the table selection the table customer is found

![EfDesigner2](https://user-images.githubusercontent.com/56717659/67078604-e5d4ef00-f191-11e9-95f9-5941844f1627.PNG)

As you can see in the edmx the table customer is not created, neither using code first method

![EfDesigner3](https://user-images.githubusercontent.com/56717659/67078605-e5d4ef00-f191-11e9-9d9b-0961fc37188d.PNG)

Meanwhile in the sql server diagram it is ok

![EfDesigner4](https://user-images.githubusercontent.com/56717659/67078607-e66d8580-f191-11e9-8eff-1bfed51b173f.PNG)

### Further technical details
EF version: 6.2 
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.17

**Comment by ajcvickers** [comment]
@lajones Please investigate this and/or ask for more info as needed.

**Comment by ajcvickers** [comment]
Ping @lajones

**Comment by lajones** [comment]
@oidocrop2019 My apologies for the long delay - I had missed this one.

I haven't done a complete investigation but here's what I think is going on: it thinks that `Customers` is the join-table between `Registries` and `Suppliers` and hence is not including it. This is probably because of the `FK_dbo.Customers_dbo.Registries_Id` and `FK_dbo.Customers_dbo.Suppliers_SupplierId` indexes on `Customers`.

I know this is a bit of a pain, but as a workaround the following should work:
1. Start from scratch and create your model with `Customers` selected and  _one_ of (but _not_ both) `Registries`  and `Suppliers` selected. This will give you a model with `Customers` on it.
2. Once your model has been created and saved off, select the background of the designer and choose "Update Model from Database". Go through the wizard again and now select whichever of `Registries`  and `Suppliers` you did not select the first time and again save the model. This should add in whichever entity was missing after step 1, but keep the `Customer` entity.

That worked for me but please let me know how it goes for you.

**Comment by lajones** [comment]
P.S. You probably should _not_ select the `__MigrationHistory` table - that is an internal table which EF uses to keep track of migrations. It is not recommended for the application to update it itself.
