### ISSUE TITLE
Renaming table doesn't rename foreign keys, future dropping of those foreign keys fails.

### ISSUE THREAD

**Issue by scott-smith-homie** [aspnet/EntityFramework6#1443]
What:
When doing Code-first migrations, if you rename a table that has foreign keys, the object name of those keys isn't updated to the new table name. Subsequent changes to those keys (like dropping the field) fails to remove the foreign key because it assumes the name of the key uses the new table name instead of the old one.

Fix:
When creating a migration for renaming a table, ensure any objects that use that table name, such as foreign keys, are also renamed so that subsequent operations against those keys don't fail because the name context is lost.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
