### ISSUE TITLE
Navigation property does not preserve setting null if it wasn't lazy loaded

### ISSUE THREAD

**Issue by OneWayLaplacesDemon** [aspnet/EntityFramework6#1447]
Assigning null value to virtual property before it is lazy loaded does not preserve the null assignment.
When you look at the code, you may not believe it probaly at first glance.
```c#
            p2.LastSchool = null;
```
No exceptions thrown, only data is not nullified as expected.

### Steps to reproduce

1. We have an entity with lazy loaded navigation property.
2. We do not check what is in navigation property because we already know we need to make it null. 
3. We believe null will be saved to database - which is not the case.
4. Expected boolean writelines are True, True, True, while they are: True, False, True.
5. Saving changes to database does not have impact on observed issue (please comment out second null assignment to p2.LastSchool to observe issue).
6. If you put breakpoint and try to peek navigation property or change tracker you will trigger lazy loading and not observe the issue.

Additional script to check and quickly restore sample db if you uncomment save changes
```sql
SELECT * FROM Person;
SELECT * FROM School;

UPDATE Person
SET [Name] = 'P2'
WHERE Id = 2;
UPDATE Person
SET LastSchoolId = Id;
UPDATE School
SET [Name] = CONCAT('School ', Id);
```

I've sample solution with 2 projects:
1. Database initialized in localdb with seed data.
2. Application showing the issue.

[NullSetter.zip](https://github.com/aspnet/EntityFramework6/files/3811593/NullSetter.zip)

### Further technical details
EF version: 6.0, 6.2, 6.4-preview 
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10, Windows Server 2012
IDE: Visual Studio 2017 15.6

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
