### ISSUE TITLE
Datatable to UDT

### ISSUE THREAD

**Issue by JoostKingma** [aspnet/EntityFramework6#1448]
Not so much a bug but more question/suggestion?

In my application I have a datatable with 600 ish rows that I want to use as a user defined table in a sql query.

Right now it gets generated as:
```sql
declare @p27 dbo.someNameUDT
insert into @p27 values(1,N'Y',1,1,N'BK',NULL,NULL,0,N'something',NULL)
insert into @p27 values(1,N'Y',1,2,N'ZO',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,3,N'BP',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,4,N'AP',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,5,N'AG',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,6,N'BD',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,7,N'GA',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,8,N'WB',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,9,N'OV',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,10,N'RW',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,11,N'WR',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,12,N'WW',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,13,N'GR',NULL,NULL,0,N'-',NULL)
insert into @p27 values(1,N'Y',1,14,N'WI',NULL,NULL,0,N'-',NULL)
```

However as far as I know it could gain a lot of performance if it was written as a single statement like:
```sql
declare @p27 dbo.someNameUDT
insert into @p27 values(1,N'Y',1,1,N'BK',NULL,NULL,0,N'something',NULL),
(1,N'Y',1,2,N'ZO',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,3,N'BP',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,4,N'AP',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,5,N'AG',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,6,N'BD',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,7,N'GA',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,8,N'WB',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,9,N'OV',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,10,N'RW',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,11,N'WR',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,12,N'WW',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,13,N'GR',NULL,NULL,0,N'-',NULL),
(1,N'Y',1,14,N'WI',NULL,NULL,0,N'-',NULL)
```

So I'm wondering why it is generated as version 1 instead of 2? Does it have to do with other database providers?

### Steps to reproduce
This is a simplified version of the code I used
```c#
DataTable dataTable = new DataTable();
dataTable .Columns.Add("col1", typeof(int));
dataTable .Columns.Add("col2", typeof(string));
dataTable .Columns.Add("col3", typeof(int));
dataTable .Columns.Add("col4", typeof(int));
dataTable .Columns.Add("col5", typeof(string));
dataTable .Columns.Add("col6", typeof(decimal));
dataTable .Columns.Add("col7", typeof(decimal));
dataTable .Columns.Add("col8", typeof(bool));
dataTable .Columns.Add("col9", typeof(string));
dataTable .Columns.Add("col10", typeof(string));
for(int i=1;i<=14;i++)
{
    dataTable .Rows.Add(1,"Y",1,i,null,null,null,null,"-",null); 
}
List<SqlParameter> Parameters = new List<SqlParameter>();

Parameters.Add(new SqlParameter("@AName", SqlDbType.Structured) { Value = dataTable , TypeName= "dbo.someNameUDT" });

dbContext.Database.ExecuteSqlCommand("Select * from @AName",Parameters);
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.16

**Comment by JoostKingma** [comment]
This is an interesting article that looks at the performance of insert statements
https://www.red-gate.com/simple-talk/sql/performance/comparing-multiple-rows-insert-vs-single-row-insert-with-three-data-load-methods/

it's a few years old but should still be relevant.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
