### ISSUE TITLE
HasDefaultValueSql in primitive properties and DefaultValueSqlAttribute

### ISSUE THREAD

**Issue by JoseCMRocha** [aspnet/EntityFramework6#145]
Is there a possibility to give the default value sql trough an attribute or primitive method configuration for the default value sql (HasDefaultValueSql)?

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
One way you could work around this is to create you own extension method that adds an annotation to the model to store the default value SQL (and maybe a convention to detect attributes and add the annotation too). This would flow through to migrations, and you could look at extending the migrations pipeline to render this nicely in the generated migration. 

One extension point you could look at is customizing the code generator - https://romiller.com/2012/11/30/code-first-migrations-customizing-scaffolded-code/.
