### ISSUE TITLE
Multiple T-SQL GO statement issue

### ISSUE THREAD

**Issue by mkorsukov** [aspnet/EntityFramework6#1472]
EF 6.1.3 doesn't support multiple `GO` statements in a T-SQL script / file. Running migration with attached script (from assembly resources) that looks like:

```
GO

// T-SQL code / stored procedure

GO
```

ends with an error:

```
Applying explicit migration: 201911042356282_Abc.
System.Data.Entity.Migrations.Design.ToolingException: The argument 'sql' cannot be null, empty or contain only white space.
at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
at System.Data.Entity.Migrations.Console.Program.Run()
at System.Data.Entity.Migrations.Console.Program.Main(String[] args)
```

### Research

- If we remove the first `GO` statement, everything works fine.
- The EF's `SqlServerMigrationSqlGenerator.cs` class brakes script into batches, but doesn't skip empty one, throwing an exception instead.

### Further technical details
- EF version: 6.1.3
- Database Provider: EntityFramework.SqlServer
- Operating system: Windows 10 to Windows Server 2012

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
