### ISSUE TITLE
EF Lazy Loading silently prevents nullable foreign key being set to NULL

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1490]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/829433/ef-lazy-loading-silently-prevents-nullable-foreign.html)._

---
If you try to set a lazy loaded (virtual) foreign key navigation property to null on an EF Entity (I believe this applies to EF6 and Core), the call to **SaveChanges()** does nothing.

This is because the property is already null because it hasn't been loaded yet, so setting it to null and calling SaveChanges() does nothing.

You need to force the property to load, and then assign null to it and call SaveChanges().

Consider the following code:

```
public void UnassignSubscription(int subscriptionId)
        {
            var user = db. Users.FirstOrDefault(x => x.Subscription.SubscriptionId == subscriptionId);

if (user != null)
            {
                user. Subscription = null;
                db. SaveChanges();
            }
        }
```

This won't work because **user. Subscription** is already null because it is virtual and hasn't been loaded yet.

The following will work because it forces **user. Subscription** to be loaded. I.e. not null.

```
public void UnassignSubscription(int subscriptionId)
        {
            var user = db. Users.FirstOrDefault(x => x.Subscription.SubscriptionId == subscriptionId);

if (user != null)
            {
                var subscription = user. Subscription; // Need to load the subscription so we can NULL it.
                user. Subscription = null;
                db. SaveChanges();
            }
        }
```

The solution would be either to auto load the property on assignment.

Or at a minimum, add the scenaro to intellisense so that you get a red squiggle to tell you your code isn't going to do anything unless you force load the property.

---
#### Visual Studio Feedback System on 11/22/2019, 00:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
