### ISSUE TITLE
Thread contention on ValidateProxyType

### ISSUE THREAD

**Issue by raulcaj** [aspnet/EntityFramework6#1500]
I took a stack trace of a application which was running slow and it turns out that most of time was spent waiting on EntityProxyFactory.GetProxyType ReaderWriterLockSlim lock.

Here is a reverse flamegraph of it. The ReaderWriterLockSlim lock is highlighted in purple.
![image](https://user-images.githubusercontent.com/4787142/69870048-660c6b00-128d-11ea-9a51-a83970c450da.png)

The write lock was hold on this stack:
![image](https://user-images.githubusercontent.com/4787142/69870138-b1bf1480-128d-11ea-9d9e-b2aefe7c1651.png)

It seems odd to me that the expression "if (identityType != actualType)" always evaluated to false so that " EntityProxyFactory.GetProxyType(entityType, MetadataWorkspace);" was called helding the write lock.

### Steps to reproduce
I'd like some insight of how "if (identityType != actualType)" inside ValidateProxyType can evaluate to false so I'll be able to reproduce it.

### Further technical details
EF version: 6.0.1304.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows Server 2012

**Comment by ajcvickers** [comment]
EF6 is mostly in a maintenance mode. One of the things this means is that we will not be making any changes that have significant risk of breaking existing, working applications. We believe changes in this area fall into that category.

**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base. 

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
