### ISSUE TITLE
Update-Database with -Script and -ConnectionString args falls back to default connection when provided connection string is invalid

### ISSUE THREAD

**Issue by mglace** [aspnet/EntityFramework6#1526]
### Description
I have a code-first Entity Framework 6 project that uses migrations to deploy changes.  The migrations work as expected against my local development database using the Update-Database  command.  

When deploying changes to the testing environment, I use the Update-Database command with the -Script and -ConnectionString argument so the I can validate the changes that will be made.

```
Update-Database -Script -ConnectionString "[OMITTED]" -ConnectionProviderName System.Data.SqlClient
```

After running the above command, I was getting the entire migration history rather than just the delta migrations from the previous release.  After days of investigation, I found that the Update-Database command fails silently when it has an issue connecting the specified database and seemingly falls back to the default connection (whatever that may be).  Since that default connection does not exist on my computer, the script produced includes the entire migration history (it tries to create the database from scratch).

In my case, the issue was that the password to the testing database has a special character in it that must be causing the connection string to be parsed improperly.  But the issue also occurs if you simply mistype your password or the password changes.  I was able to overcome my issue by surrounding my password with single quotes.  Doing so allowed the Update-Database command to connect to the testing database and produce the correct change script.

I found this to be extremely confusing and I hope that this helps anyone else that may run into this issue.

### Further technical details
EF version: 6.2.0
Database Provider: System.Data.SqlClient
Operating system: (e.g. Windows 10) 
IDE: Visual Studio 2019 v16.4.0

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
