### ISSUE TITLE
Return nullable entity When the sql data of first column is null

### ISSUE THREAD

**Issue by lic0914** [aspnet/EntityFramework6#1529]
Hi 
   It is a strange phenomenon when I used the lambda expression to query data and  return null entity . However it is has one line data when I got the sql translating to execute . I have analysed carefully the sql discovering the sql of one column is null .
 Is it a bug or having other reasons.
I had another question the sql  translating  columns sort is not same
for example

``` sql
select name ,id from (
    select top 1 id ,name from user 
) temp 
```
the wraped sql column sort is not same intenal sql  .
when the column for 'name' is null ,ef return nullable entity,because the 'name' is first column .
Thanks!

EF version:6.0.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2019 lasted

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by lic0914** [comment]
> **EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?
> 
> > ### Steps to reproduce
> 
> Ideally include a complete code listing that we can run to reproduce the issue.
> Alternatively, you can provide a project/solution that we can run.
> 
> BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.
> 
> For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).
> 
> _BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions._

I am so sorry !It's my fault because EntityConfig used HasRequired ,It should use HasOptional !
Thank you for your reply
