### ISSUE TITLE
Issues with escaping identifiers when building migrations

### ISSUE THREAD

**Issue by Robert-Laverick** [aspnet/EntityFramework6#1532]
In SQL Server it's valid to have any character (as far as I can tell) in an identifier. This means that you can have a table who's name includes []. While playing with this I discovered the following discrepancy with migrations.

Have two entities one called TableA and one called TableB, which are in the default dbo schema. Everything works as expected. Add a Table attribute to TableB to specify a name like this:

[Table("[[dbo]].[TableA]]]")]

This means that the table name for TableB is [[dbo]].[TableA] in the dbo schema.

Create a migration, using "Add-Migration DbaHate" and it creates the following migration.

```
    public partial class hate : DbMigration
    {
        public override void Up()
        {
            RenameTable(name: "dbo.TableB", newName: "[dbo].[TableA]");
        }
        
        public override void Down()
        {
            RenameTable(name: "dbo.TableA", newName: "TableB");
        }
    }
```

Applying this migration fails, because although it's not showing it EF is trying to rename the Primary Key for Table B to be the same as the Primary Key for Table A. this seems to be because the auto name generation for the index is incorrectly generating none unique names for the two tables. as it's double decoding the string name of the table.

In my original case I didn't have that issue as I'm using the onmodelcreating to give the keys specific names, so adding these to the context does allow the migration to apply, and then the application works as expected.

```
            modelBuilder.Entity<TableA>().HasKey(c => c.Id, pki => pki.HasName("PK_dbo_TableA"));
            modelBuilder.Entity<TableB>().HasKey(c => c.Id, pki => pki.HasName("PK_dbo_TableB"));
```

The real problem comes if you try to revert the migration (because let's be honest there's no way I want this to stay in my database) the down migration runs just fine but it is causing the original "TableA" object to be renamed as "TableB" and leaving the new "[dbo].[TableA]" to be left as is. This leaves the app unable to run because the table names don't match EF and it doesn't work anymore.

So the Issue comes down to inconsistent application of escaping when generating migrations. rename seems to handle the name and newName arguments differently too which is probably where some of the issue comes from, but the fact that index names aren't correctly handled too makes this seem like it's something that's happening elsewhere too. I'm not clear if the issue is confined to things that are optionally taking a schema as part of the name (as TableAttribute seems to for example) but I think suspect that once you look under the hood there might be other ways to trigger this kind of issue.

EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE:Visual Studio 2019 16.4.2

PS: I'd like to apologise to anyone offended by the table names generated in this bug report, and any sense of dread that they may cause.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
