### ISSUE TITLE
DefaultIfEmpty mess with OrderBy

### ISSUE THREAD

**Issue by RafaelSalguero** [aspnet/EntityFramework6#167]
The following query is returned correctly ordered:
```
c.Transactions
.OrderByDescending(x => x.Date)
.Select(x => x.Acum)
.ToList();
```
But this other query not:

```
c.Transactions
.OrderByDescending(x => x.Date)
.Select(x => x.Acum)
.DefaultIfEmpty()
.ToList();
```

These are the generated SQLs for both queries, as you can see the second doesn't have an ORDER BY clause:

```
SELECT "Extent1"."Acum" 
FROM "public"."Transactions" 
AS "Extent1" ORDER BY "Extent1"."Date" DESC  
```

```
SELECT  CASE  
WHEN ("Project1"."C1" IS NULL) 
THEN (0::numeric) 
ELSE ("Project1"."Acum") END  AS "C1" 
FROM (SELECT 1 AS "C") AS "SingleRowTable1" 
LEFT OUTER JOIN 
(SELECT "Extent1"."Acum", 1::int2 AS "C1" FROM "public"."Transactions" AS "Extent1") AS "Project1" 
ON TRUE = TRUE
```

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
BTW the workaround is to move the `DefaultIfEmpty` call to after the `ToList`, which is arguably better as there is no need for the replacement of an empty result set to be done in the database.

```c#
c.Transactions
.OrderByDescending(x => x.Date)
.Select(x => x.Acum)
.ToList()
.DefaultIfEmpty();
```

**Comment by rowanmiller** [comment]
The code listed didn't seem like a very common case to us, `DefaultIfEmpty` is typically used on optional navigation properties. But we were curious if the code provided was a simplification of a scenario that may be more common? If so, we would reconsider addressing this issue.

**Comment by RafaelSalguero** [comment]
The code is common on situations when a table have a column with some accumulate, when the absence of rows indicates an accumulate of 0.

The first example was simplified, usually the `DefaultIfEmpty` call can't be done in-memory since its being used inside a linq query

A more complete example:
```
Get all accounts, with its current balance (pseudocode)

class Account
{
   public int Id { get; set; } 
   public string Name { get; set; }
}

class Transaction
{
  public int Id { get; set; }
  public DateTime Date { get; set; }
  public decimal Amount { get; set; }
  public int IdAccount { get; set; }

  //Each transaction have the account balance at the moment after the transaction
  public decimal Accum { get; set; }
}

class AccountDTO : Account
{
  public decimal Balance { get; set; }
}

//Get all accounts with its balances:
public List<AccountDTO> GetAccountBalances(Context c)
{
  return c
  .Accounts
  .Select(x => new AccountDTO 
  {
    Id = x.Id,
    Name = x.Name,
    Balance = c.Transaction.OrderByDescending(t => t.Date).Select(t => y.Accum).DefaultIfEmpty()
  })
  .ToList();
}
```
