### ISSUE TITLE
Investigate potential inefficiencies in around CLR null semantics

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework6#168]
Repro provided by customer:

Hello,

I have the following code:

```IDbSet<User> users = ((DatabaseContext) Context).GetSet<User>();
List<User> matchingUsers = new List<User>(users.Where<User>((u) => u.PublishingUserName == publishingUserName));
return matchingUsers.FirstOrDefault<User>();
```

It generates the following query:

```SELECT       
[Extent1].[Id] AS [Id],       
 [Extent1].[UserName] AS [UserName],       
[Extent1].[PublishingUserName] AS [PublishingUserName],       
[Extent1].[PublishingPassword] AS [PublishingPassword],       
[Extent1].[LastUpdatedTime] AS [LastUpdatedTime],       
FROM [dbo].[Users] AS [Extent1]      
WHERE (([Extent1].[PublishingUserName] = @p__linq__0) AND ( NOT ([Extent1].[PublishingUserName] IS NULL OR @p__linq__0 IS NULL))) 
OR (([Extent1].[PublishingUserName] IS NULL) AND (@p__linq__0 IS NULL))
```

The presence of the NULL checks in the query causes SQL not to use the non-clustered index and makes the query very inefficient. 

What we expect to happen is:

```
SELECT       
[Extent1].[Id] AS [Id],       
 [Extent1].[UserName] AS [UserName],       
[Extent1].[PublishingUserName] AS [PublishingUserName],       
[Extent1].[PublishingPassword] AS [PublishingPassword],       
[Extent1].[LastUpdatedTime] AS [LastUpdatedTime],       
FROM [dbo].[Users] AS [Extent1]      
WHERE [Extent1].[PublishingUserName] = @p__linq__0 OR ([Extent1].[PublishingUserName] IS NULL AND @p__linq__0 IS NULL)

```

**Comment by rowanmiller** [comment]
We'll investigate to see if there is an easy fix.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
