### ISSUE TITLE
Migration not refreshing PK nor FKs on schema rename

### ISSUE THREAD

**Issue by DarioFederico** [aspnet/EntityFramework6#169]
I have the following scenario:
A table allocated in the standard dbo schema of a SQL Server 2012 database.
Then I want to move it to a new schema, so I setup the EntityTypeConfiguration by writing `ToTable("TableName", "newSchema")`.
I add a new migration, and it only generates the sentence `MoveTable(name: "TableName", newSchema: "newSchema");`
So far, there appears to not be necessary any other rename of any other object in the database due to the table being moved to a new schema.
I apply the change and everything works well. Table is moved from one schema to the other, but I noticed that the PK name still says "_PK_dbo.TableName_".

Then I make another change to my model. Let's say for instance that I change the PK type, from long to int.
Now I create a new migration and it correctly includes the `DropPrimaryKey()` sentence on it, with all schema and table names as they are.
Now when I run the `update-database -verbose`, I noticed that it tries to run the following SQL: 
`ALTER TABLE [newSchema].[TableName] DROP CONSTRAINT [PK_newSchema.TableName]`
With the following error message: **System.Data.SqlClient.SqlException (0x80131904): 'PK_newSchema.TableName' is not a constraint.**

Now, of course that's not the real name of my previous PK (remember it was still **PK_dbo.TableName**). 

Entity Framework is actually trying to alter objects with a _calculated_ name, instead of picking the _real_ ones from the database!! 

Is this something already known or is there some direct solution/workaround?
Thanks.

**Comment by DarioFederico** [comment]
@CesarD

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
This issue stems from some limitations in how migrations is architected in EF6.x. The constraint names are not part of the model, so migrations has to "guess" what they are when it needs to drop them (it does that by using the constraint naming conventions with the current model). This is also the reason we don't perform a rename of the constraints when the table is moved. To make it worse, we don't currently have the previous model when we do the table move, so that prevents generating a "guess" of the constraint renames based on conventions (since we don't know the old names).

Unfortunately this means that addressing this would be a huge job on EF6. In EF Core we addressed these limitations in the architecture and the scenario works as you would expect. The correct workaround is to manually edit the migration file... the easiest place to do this would be the `DropPrimaryKey` call where we "guess" the wrong name.
