### ISSUE TITLE
Length of string parameters on where clause

### ISSUE THREAD

**Issue by frbatist** [aspnet/EntityFramework6#176]
I have the following mapping for a varchar column:

`modelBuilder.Entity<Empresa>().Property(p => p.Codigo).HasColumnName("EMPCOD").HasMaxLength(4).IsFixedLength();`

And I'm ending up with a parameter like this one:
@p__linq__0 varchar(8000)

Is there any chance to fix this so that the parameter is created the wright way ?
Like this :
@p__linq__0 varchar(4)

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by divega** [comment]
PR was submitted for this: https://github.com/aspnet/EntityFramework6/pull/181/. Reopening so that we can evaluate it.

**Comment by rowanmiller** [comment]
Putting in 6.3.0 on the basis of the PR. It's not something our team is planning to do.

**Comment by ajcvickers** [comment]
Closing for now. Will re-open if the PR gets to a state in which it can be merged.
