### ISSUE TITLE
Unnecessary LEFT OUTER JOIN with Table Per Type

### ISSUE THREAD

**Issue by schweinsbauch** [aspnet/EntityFramework6#183]
In "complex" polymorphic scenarios, a unnecessary LEFT OUTER JOIN is generated:

```
SELECT 
    [Extent1].[BaseSlaveId] AS [BaseSlaveId], 
    CASE WHEN ((CASE WHEN (([Project1].[C1] = 1) AND ([Project1].[C1] IS NOT NULL)) THEN cast(1 as bit) WHEN ( NOT (([Project1].[C1] = 1) AND ([Project1].[C1] IS NOT NULL))) THEN cast(0 as bit) END) <> 1) THEN '0X0X' ELSE '0X0X0X' END AS [C1], 
    [Extent3].[BoolProperty] AS [BoolProperty], 
    [Extent3].[IntProperty] AS [IntProperty], 
    [Extent1].[SlaveADouble1] AS [SlaveADouble1], 
    [Extent1].[SlaveADouble2] AS [SlaveADouble2], 
    [Extent1].[SlaveAString] AS [SlaveAString], 
    CASE WHEN ((CASE WHEN (([Project1].[C1] = 1) AND ([Project1].[C1] IS NOT NULL)) THEN cast(1 as bit) WHEN ( NOT (([Project1].[C1] = 1) AND ([Project1].[C1] IS NOT NULL))) THEN cast(0 as bit) END) <> 1) THEN CAST(NULL AS int) ELSE [Project1].[Unit] END AS [C2], 
    [Extent3].[Master_MasterId] AS [Master_MasterId]
    FROM    [dbo].[SlaveAs] AS [Extent1]
    LEFT OUTER JOIN  (SELECT 
        [Extent2].[BaseSlaveId] AS [BaseSlaveId], 
        [Extent2].[Unit] AS [Unit], 
        cast(1 as bit) AS [C1]
        FROM [dbo].[SlaveASubs] AS [Extent2] ) AS [Project1] ON [Extent1].[BaseSlaveId] = [Project1].[BaseSlaveId]
    INNER JOIN [dbo].[BaseSlaves] AS [Extent3] ON [Extent1].[BaseSlaveId] = [Extent3].[BaseSlaveId]
    LEFT OUTER JOIN [dbo].[SlaveBSub1s] AS [Extent4] ON [Extent1].[BaseSlaveId] = [Extent4].[BaseSlaveId]
    WHERE ([Extent1].[SlaveADouble1] < (@p__linq__0 + cast(0.1 as float(53)))) AND ([Extent1].[SlaveADouble1] > @p__linq__1)
```

Following class hierarchy is used:

class Master may have many Slaves (BaseSlave).
a Slave(BaseSlave) has one Master.

Following classes for Slaves exist:
BaseSlave

SlaveA : BaseSlave
SlaveASub : SlaveA

SlaveB : BaseSlave
SlaveBSub1 : SlaveB
SlaveBSub2 : SlaveB

For Details see the attached sample.

[TablePerType.zip](https://github.com/aspnet/EntityFramework6/files/726788/TablePerType.zip)

[Entityframework 6.1.3 is used]

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
This change would be very high risk and the current SQL is functional, just not optional.
