### ISSUE TITLE
SQL Parameter type when inserting to date column

### ISSUE THREAD

**Issue by unter** [aspnet/EntityFramework6#187]
### Issue
I have a simple database table with a column defined as type date that is being encrypted using Always On encryption.

The column definition looks like this:

`[DateOfBirth] [date] ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = [KeyName], ENCRYPTION_TYPE = Deterministic, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL,`

In my OnModelCreating override I am setting the column type to be date:

` modelBuilder.Entity<DataObject>().Property(p => p.DateOfBirth).HasColumnType("date");`

Creating a new object and performing SaveChanges on the DbContext throws the following error:

> {"Operand type clash: datetime2(7) encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'KeyName', column_encryption_key_database_name = 'DbName') is incompatible with date encrypted with (encryption_type = 'DETERMINISTIC', encryption_algorithm_name = 'AEAD_AES_256_CBC_HMAC_SHA_256', column_encryption_key_name = 'KeyName', column_encryption_key_database_name = 'DbName')\r\nStatement(s) could not be prepared."}

Entity Framework is setting the parameter type in the insert statement to datetime2 instead of date.

The log for the parameter looks like this:

> -- @3: '1/1/2001 12:00:00 AM' (Type = DateTime2)

Using a SQL Command I can successfully insert to the table by setting the parameter type correctly like this:

`SqlParameter param = new SqlParameter("@DateOfBirth", System.Data.SqlDbType.Date);
            param.Value = DateTime.Now.Date;`

### Further technical details

- EF 6.1.3
- SQL Server 2016 (13.0.4199)
- SQL Always On Encryption
- Azure Key Vault
- VS2015 with latest update

**Comment by ErikEJ** [comment]
I think you will have to change the column data type to datetime2 in the short run...

**Comment by unter** [comment]
I have switched to datetime2 for now but I wanted to post the issue because it will probably be a problem for others trying to use Always On encryption.

**Comment by ErikEJ** [comment]
Sure. What .net type would you use to represent the SQL "date" type?

**Comment by unter** [comment]
I'm using DateTime.

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by rowanmiller** [comment]
The recommendation is to use `datetime2` columns

**Comment by vijjusree** [comment]
So how can we fix  the datatype for BIRTH_DATE datetime2(7) to datetime2? Is there any size matters when encryption is done on deterministic ?
