### ISSUE TITLE
DbContext this.Database.Intialize(true) failure

### ISSUE THREAD

**Issue by dlipkie** [aspnet/EntityFramework6#191]
I have a designer created model class shown below. 

I create an instance of this class
    ShellLdsModel myModel = new ShellLdsModel()
use it and then myModel goes out of scope which should discard the instance. The Database.Intialize(true) causes OnModelCreating() to be invoked, as expected.

I then again create an instance of this class in the same way but this time OnModelCreating() is not invoked and I get an error when I try to use a DbSet<entity>, 
   The entity type <entityName> is not part of the model for the current context
I think this is because OnModelCreating() did not get called to add the DbSet<entity> via FluentAPI.

Any suggestions/ideas?

    public partial class ShellLdsModel : DbContext
    {
        public ShellLdsModel()
            : base("name=ShellLdsModel")
        {
            // Add this to avoid
            // Field not found: 'OracleInternal.Common.ODTSettings.m_bUseLongIdentifiers'.
            Database.SetInitializer<ShellLdsModel>(null);
            // Do this to force OnModelCreating to be called NOW 
            // instead on first use of a DbSet to get data
            this.Database.Initialize(true); 
        }
        ...
   }

**Comment by rowanmiller** [comment]
By default the model is created once and then cached. Each subsequent instance of the same context type just uses the cached model, rather than running the expensive model building pipeline again.

You can control the cache key though, if different instances of the same context type should have different models. See the first answer on this StackOverflow thread - http://stackoverflow.com/questions/30095663/emit-dbcontext-onmodelcreating-on-every-context-creation.
