### ISSUE TITLE
Reconsider CodeAnalysis for EF6

### ISSUE THREAD

**Issue by lajones** [aspnet/EntityFramework6#206]
The code in EF6 now has many CodeAnalysis suppressions. The most recent especially suppressed a lot of code of the form:

```
Debug.Assert(x is ClassXyz);
DoSomething(x as ClassXyz);
```

but there are many suppressions of many different types throughout both the runtime and the tools.

This issue is to reanalyze the costs and benefits we are getting from CodeAnalysis, and to decide a) whether to continue running it, b) if so how should we approach common situations where suppressions are often necessary, c) revisiting the code to apply these rules.

Bear in mind that we still run CodeAnalysis against Dev11, Dev12, Dev14 and Dev15 - and that both the CodeAnalysis DLLs and the way the rules are applied have changed since Dev11. Also bear in mind CodeAnalysis often produces different results for release builds versus debug builds.

**Comment by divega** [comment]
I saw a comment in the PR from @ajcvickers saying that in the past we used not to do CodeAnalysis on debug builds because that resulted in a lot of noise. Did we start at some point doing it? Or are all these issues popping up because of some other change in VS?

**Comment by lajones** [comment]
Actually its the release builds that tend to cause more noise - e.g. because code which uses variables is no longer there - and maybe also because most developers are generally working in debug mode - so it's the debug mode errors they see. We currently skip CodeAnalysis when doing CI release builds (and we are still doing that even after my PR) for the same reason.

**Comment by ajcvickers** [comment]
@lajones @divega Issues on release builds are always valid in the sense that FxCop is flagging something that is happening in the actual code that we ship. (We may disagree that what it is flagging is something that should be changed, but that is true of any code analysis.) On the other hand, issues on debug views can be entirely an artifact of debug code--as is the case in the example in the description of this bug. This is why historically we have only run FxCop on release builds--because we care about what we ship, and we don't care if debug code introduces artifacts that have no impact on what we ship.

While it is true that FxCop can flag issues in code we release because of code we have for debugging, that is actually a good thing. It indicates that debug code is impacting what we ship, and this is something we should fix.

**Comment by rowanmiller** [comment]
We decided not to do anything right now.
