### ISSUE TITLE
Make DbContext.Entry virtual

### ISSUE THREAD

**Issue by ADringer** [aspnet/EntityFramework6#208]
Hi,

When unit testing I can mock out SaveChanges(), Set() etc fine so I don't go to the database. However, I am unable to mock out Entry() as this has not been set to virtual.

Is there a reason why this isn't virtual? I can see in EFCore that it is so was wondering if there is a plan to make this method virtual?

Thanks

Alex

**Comment by rowanmiller** [comment]
Are you sure that this will help? The Entry method returns an EntityEntry which is not setup to be mocked like DbSet is (nor are any of the related classes - such as PropertyEntry etc.). Would a virtual Entry method (a trivial change for us to make) help or would you need all the associated classes setup for mocking ( a more involved change)?

**Comment by ADringer** [comment]
I want to mock out the Entry method so it doesn't actually go to the database, which I believe the InternalContext is doing?

I want to mock out the following line:
`_context.Entry(entity).State = EntityState.Modified;`
And I want to mock Entry to do pretty much nothing, I'm not interested in the rest of the behaviour, I'm just testing my code.

So if Entry was virtual, I would mock it to return a DbEntityEntry which would let me set the State without actually do any of the internal workings of EF. But it looks like it isn't as simple as making Entry virtual as DbEntityEntry's constructor is internal so can't actually create an instance?

Doesn't look like it is as simple as making Entry virtual, as I wouldn't be able to do anything with the return object. If it would require all the associated classes for mocking then maybe I need to refactor my code!

**Comment by rowanmiller** [comment]
Yeah, we've discussed this in the past. DbSet is setup to be faked/mocked, but it was quite a bit of work to do that, and EntityEntry and it's associated classes would be more complicated. BTW in EF Core we took a different approach of having an InMemory provider, so you don't have to mock/fake things.

If folks wanted to make incremental changes to enable mocking EntityEntry, we'd be open to the pull requests. The approach would want to be consistent with how we did DbSet. It's not something our team is planning to do though.

**Comment by asartem** [comment]
@rowanmiller 

> DbSet is setup to be faked/mocked, but it was quite a bit of work to do that,

It's much more easy to mock and handle with db set when you have an IQuariable<T> result and use repo like;
MyItemRero.Where(x=>Name == "something").ToList();
If you mock DB set, then all you need is to setup a list of correct Items which can filtered

If you mock whole repository, you need to pass a correct Expression<Func<T,bool>> to you Where(). 
It's so hard, that almost not possible to implement (with It.Is<T>(c=>c...), not with It.IsAny<T>).
Because different parts of code MyItemRero.Where() may return different values using different criteria plus paging(Take() and Skip()).
I know about extracted expression tree and compare it. It doesn't work (well) by some unknown reason. Only It.IsAny<Expression<Func<T,bool>>> works. And it's additional complicated situation with compare of expression tress instead of simple mocking DBSet or Entry when I need to mock   Repository.Update.
