### ISSUE TITLE
Combinatorial explosion or parameter duplicates

### ISSUE THREAD

**Issue by george-polevoy** [aspnet/EntityFramework6#211]
When used multiple times in a queue, parameters are duplicated.

When query is reused as a code unit in a top-level query, all of the parameters of the lower-level queue are copied for each usage, so if used twice in a top-level queue, then the number of parameters from a lower-level queue will be multiplied by the number of usages.

```C#
        var parameter = 0;
	
	// just some nonesence q based on sys.Columns in SQL Server as some table common to everyone.
	var q =
		from c in Columns
		where
			c.Column_id == parameter || c.Default_object_id == parameter
		select c;
		
	var q2 =
		from a in q
		from b in q
		where b.Column_id > parameter
		select new { a, b };
		
	// Guess what number of parameters you get?
	// DECLARE @p0 Int = 0
	// DECLARE @p1 Int = 0
	// DECLARE @p2 Int = 0
	// DECLARE @p3 Int = 0
	// DECLARE @p4 Int = 0
	// ... WHERE ([t1].[column_id] > @p0) AND (([t0].[column_id] = @p1) OR ([t0].[default_object_id] = @p2)) AND (([t1].[column_id] = @p3) OR ([t1].[default_object_id] = @p4))
```

A real-world example (expanding of a hierarchy down to 6 levels):

```C#
        var start = new DateTime(2017, 02, 28, 11, 30, 00);
	var end = new DateTime(2017, 02, 28, 11, 31, 00);

	var procInstCriteriaQ =
		from p in *****CLASSIFIED*****
		where p.StartTime < end && p.ModifiedTime >= start
		select // ....

	var processInstanceHierarchyQ =
		from p1 in procInstCriteriaQ		
		join p2 in procInstCriteriaQ on p1.Id equals p2.ParentId into c1 from p2 in c1.DefaultIfEmpty()
		join p3 in procInstCriteriaQ on p2.Id equals p3.ParentId into c2 from p3 in c2.DefaultIfEmpty()
		join p4 in procInstCriteriaQ on p3.Id equals p4.ParentId into c3 from p4 in c3.DefaultIfEmpty()
		join p5 in procInstCriteriaQ on p4.Id equals p5.ParentId into c4 from p5 in c4.DefaultIfEmpty()
		join p6 in procInstCriteriaQ on p5.Id equals p6.ParentId into c5 from p6 in c5.DefaultIfEmpty()
		select new {
			p1,
			p2,
			p3,
			p4,
			p5,
			p6,
			};
	
	var processHierarchyFlattenedQ = processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p1 })
	.Concat(processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p2 }))
	.Concat(processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p3 }))
	.Concat(processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p4 }))
	.Concat(processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p5 }))
	.Concat(processInstanceHierarchyQ.Select(i => new { startingNode = i.p1, actualNode = i.p6 }))
	.Select(p => p.actualNode);

var q =
		from e in // ....
		where processHierarchyFlattenedQ.Select(p => p.Id).Contains(e.ProcessInstanceId)
```
The two DateTime parameters here exploded to:

```SQL
DECLARE @p__linq__2 DateTime2 = '2017-02-28 11:31:00.0000000'
DECLARE @p__linq__3 DateTime2 = '2017-02-28 11:30:00.0000000'
DECLARE @p__linq__4 DateTime2 = '2017-02-28 11:31:00.0000000'
DECLARE @p__linq__5 DateTime2 = '2017-02-28 11:30:00.0000000'
DECLARE @p__linq__6 DateTime2 = '2017-02-28 11:31:00.0000000'

-- 72 in total
```

**Comment by ajcvickers** [comment]
@smitpatel Can you try this in EF Core and see how we behave there?

**Comment by smitpatel** [comment]
EF core shows the same behavior as ef6 and produces a lot of parameters. I filed https://github.com/aspnet/EntityFramework/issues/7797 to track it on EF Core.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
