### ISSUE TITLE
ASP NET Core and EntityFramework6 after upgrade to VS 2017 faling with exception

### ISSUE THREAD

**Issue by msmolka** [aspnet/EntityFramework6#214]
Hello
I know that is probably not directly related but maybe you can point me how to solve the issue.
On one computer all is working on the other not. Reverting application to VS 2015 solves the issue.
Other methods with EF working. Only one not.
The exception we have is:

`
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_Expression()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Expression()
   at System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate)
   at SyncService.<Sync>d__1.MoveNext()
`

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by msmolka** [comment]
That is a problem, this issue is strange. It occurs on one computer, and not on other. Also it is not occurring every time, only on one method, other application using ef 6 and connecting to the same db is working. Just wondered if you can point me were to look for problem.

**Comment by ajcvickers** [comment]
@msmolka From just the information provided I don't have any ideas on what the problem is or where to look for it. I would start by looking at what is different between the code/machines where it works and where it doesn't.

**Comment by msmolka** [comment]
The funny thing is all is working in asp core vs2015 but not after migrate to vs2017

**Comment by msmolka** [comment]
It is stranger and stranger. I've downgraded version EF all worked properly then upgraded again and now all is working.
