### ISSUE TITLE
Support for the  Elastic Database tools - Multi-shard querying

### ISSUE THREAD

**Issue by rlarno** [aspnet/EntityFramework6#220]
I'm not familiar with the internals of EF to find out if it would be possible/feasible to add support for the [Elastic Database Tools - Multi-shard querying](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-scale-multishard-querying).

There is already a document and support for EF for basic CRUD on a single shard: [Elastic Database client library with Entity Framework](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-elastic-scale-use-entity-framework-applications-visual-studio)

But being able to launch a query across a number of shards while still being able to use EF (and Linq) to generate the correct resultset would be a huge benefit.

Initially one would have to be able to 'provide' the `DbContext` the _MultiShard*_ types to be able to run queries. (It's a pity the [ElasticScale ](https://www.nuget.org/packages/Microsoft.Azure.SqlDatabase.ElasticScale.Client/) library is not open source, so no idea how compatible this is)

I had a quick look around and noticed EF still uses these basic types: `DbConnection`, `DbCommand`, `DbDataReader`. So perhaps there is a way to substitute the standard `SqlConnection`, `SqlCommand `and `SqlDataReader` with the `MultiShardConnection`, `MultiShardCommand` and `MultiShardDataReader`.

As [support for SQL Azure Federations](https://msdn.microsoft.com/en-us/library/jj556244(v=vs.113).aspx) is [deprecated](https://support.microsoft.com/en-us/help/3087180/federation-retirement-warning-message-in-azure-sql-database), this is now pointing back to the [Elastic Database tools](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-elastic-scale-get-started), but there is no proper solution using EF.

Can something be done by using the `DbProviderFactory` and/or `IDbProviderFactoryResolver`?

**Comment by ajcvickers** [comment]
@divega to follow up.

**Comment by ajcvickers** [comment]
@divega Do you still plan to follow up on this? (If not, I'll close as something we're not going to invest in for EF6.)

**Comment by divega** [comment]
I took a quick look. Microsoft.Azure.SqlDatabase.ElasticScale.Client is an ADO.NET provider that allows executing fan-out queries across sharded Azure SQL databases. 

I think it would require an investment on our side just to figure out what we can do with it, and then some more to implement it. Definitively, it doesn't meet the bar for doing it on EF6, and FWIW, we haven't had feedback on EF Core to do anything with this library.

On the other hand, it is possible that someone with enough understanding of this library's capabilities could write an EF6 provider around it based on how SQL Server provider EF6 is built around System.Data.SqlClient.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
