### ISSUE TITLE
Wrong navigation property mapping with Fluent API

### ISSUE THREAD

**Issue by navozenko** [aspnet/EntityFramework6#233]
Hello.
Here is a simple code that should write and read a list of users

    class User
    {
        public int Id { get; set; }
        public virtual UserType Type { get; set; }
    }

    class UserType
    {
        public int Id { get; set; }
    }

    class MyDbContext : DbContext
    {
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }

        public MyDbContext()
        {
            Database.SetInitializer(new DropCreateDatabaseAlways<MyDbContext>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserType>()
                .Property(x => x.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            modelBuilder.Entity<User>()
                .Property(x => x.Id)
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            modelBuilder.Entity<User>()
                .HasOptional(p => p.Type)
                .WithOptionalDependent()
                .Map(m => m.MapKey("user_type_id"));
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyDbContext())
            {
                var userType1 = new UserType { Id = 1 };
                var userType2 = new UserType { Id = 2 };

                db.UserTypes.Add(userType1);
                db.UserTypes.Add(userType2);
                db.Users.Add(new User { Id = 1, Type = userType1 });
                db.Users.Add(new User { Id = 2, Type = userType2 });
                db.Users.Add(new User { Id = 3, Type = userType2 });

                db.SaveChanges();
            }

            using (var db = new MyDbContext())
            {
                var users = db.Users.OrderBy(x => x.Id).ToList();
                var types = db.UserTypes.ToList();

                foreach (var user in users)
                    Console.WriteLine($"User: Id = {user.Id}, Type = {user.Type?.Id.ToString() ?? "null"}");
            }
        }
    }

An expected output is:
User: Id = 1, Type = 1
User: Id = 2, Type = 2
User: Id = 3, Type = 2

But the actual output is:
User: Id = 1, Type = 1
User: Id = 2, Type = null
User: Id = 3, Type = 2

Even stranger that if I commenting out the line `var types = db.UserTypes.ToList();`
the actual output becomes:
User: Id = 1, Type = null
User: Id = 2, Type = null
User: Id = 3, Type = null

The problem occurs only when I use mapping with `HasOptional().WithOptionalDependent()`. Without it, everything works correctly.
Is this a bug?.. or am I doing something wrong?

**Comment by ajcvickers** [comment]
@navozenko The HasOptional().WithOptionalDependent() mapping means that there can be at most one entity on either end of the relationship. In your code, userType2 is first associated with one User, and then in the next line associated with another User. This causes it to be "reparented" from one User to the next. The first User no longer has a UserType associated with it, and hence the navigation property is null. You probably want to use a one-to-many relationship instead.

With regard to your second question, the navigation properties are null because the UserTypes have not been loaded from the database. Lazy-loading doesn't kick in because your entity types are not public and so cannot be proxied.
