### ISSUE TITLE
Database.CommandTimout not applied consistently 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#24]
The value set on Database.CommandTimout is not configured on various DbCommands created on behalf of a DbContext to execute database initialization operations and to retrieve `serverproperty('EngineEdition')` on SQL Server. 

From the symptoms described at http://stackoverflow.com/questions/38317660/azure-webjob-timeout-when-calling-stored-procedure/38359399 and some internal threads it seems that this can have  customer impact, especially when using Azure SQL Database.

Note that DbMigrationsConfiguration has its own CommandTimeout property that should be applied to migration operations. 

**Workaround**

It is possible to use command interception to set the timeout, e.g.:

``` C#
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Interception;

namespace CommandTimeOutBug
{
    class Program
    {
        static void Main(string[] args)
        {
            DbInterception.Add(new MyInterceptor());

            using (var context = new ApplicationDbContext())
            {

                context.Database.CommandTimeout = 2;

                context.PopulateJobTypeDescendants();
            }
        }
    }

    public class ApplicationDbContext : DbContext
    {

        public void PopulateJobTypeDescendants()
        {
           Database.ExecuteSqlCommand("PopulateJobTypeDescendants");
        }
    }

    public class MyInterceptor: DbCommandInterceptor
    {

        public override void NonQueryExecuting(DbCommand command, DbCommandInterceptionContext<int> interceptionContext)
        {
            command.CommandTimeout = 2;
            base.NonQueryExecuting(command, interceptionContext);
        }

        public override void ReaderExecuting(DbCommand command, DbCommandInterceptionContext<DbDataReader> interceptionContext)
        {
            command.CommandTimeout = 2;
            base.ReaderExecuting(command, interceptionContext);
        }

        public override void ScalarExecuting(DbCommand command, DbCommandInterceptionContext<object> interceptionContext)
        {
            command.CommandTimeout = 2;
            base.ScalarExecuting(command, interceptionContext);
        }
    }
}
```

**Comment by ajcvickers** [comment]
Notes for triage: I investigated this and found that we use the command timeout set on the context in all cases except the following:
* When using static methods of Database, since there is no context here. We previously discussed this and decided not to do anything: https://entityframework.codeplex.com/workitem/985
* When performing Migrations operations where the timeout set in MigrationsConfiguration is used instead. This includes when using the MigrateDatabaseToLatestVersion initializer. This is by design since Migrations commands may be long running.
* During model building when `select cast(serverproperty('EngineEdition') as int)` is executed in order to determine the provider manifest token. We could plum the context timeout all the way through here, but it would require both provider and model building API changes such that when the context is using the model builder a timeout can be passed to Build, and this can then be flowed into the provider. Given that this is the command timeout (not the connection timeout) and that the command being executed is very simple it seems unlikely there will be any real benefit in doing this.

**Comment by divega** [comment]
I think there is good argument for not making changes here.
