### ISSUE TITLE
Query: No support for casting/converting string to GUID/UNIQUEIDENTIFIER

### ISSUE THREAD

**Issue by leotsarev** [aspnet/EntityFramework6#249]
I like to re-open following request 
https://entityframework.codeplex.com/workitem/1865

**Comment by leotsarev** [comment]
If this is ok, I want to understand if this change is easy enough to be completed by someone without specifc knowledge about EF codebase.

**Comment by divega** [comment]
@leotsarev have you tried comparing the Guids as text, e.g.:

``` C#
var query = db.Users.Where(user => (Guid)user.GuidText == guid.ToString());
```

Would address you needs? 

I don't think implementing the solution based on the string constructor would be too difficult, but it does require familiarity with the codebase. You may want to look at other examples in `MethodCallTranslator.cs` and try to understand how they work.

**Comment by leotsarev** [comment]
I have ```Select```, not ```Where```.
And yes, there is plenty of workarounds. I just think this should "just work".
I'll look into ```MethodCallTranslator```, thanks.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution (PR) to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
