### ISSUE TITLE
Excessive ToList calls

### ISSUE THREAD

**Issue by Backs** [aspnet/EntityFramework6#250]
Solution contains a lot of ToList calls, sometimes ther are excessive and leadt to unnecessary memory traffic and perfomance problems.
In some places it's better to use more generic types like IEnumerable<T>

**Comment by ajcvickers** [comment]
@Backs I'm sure there are places where ToList calls are unnecessary, but usually these are there by design to protect the original collection, often because there is a possibility that it will be modified while it is being iterated. For us to take any PR on this we would have to be confident that in every place the ToList is removed there will not be a regression in functionality. Running all the test would be the minimum bar for this, but because of the history of the codebase we don't have good coverage for some areas of the stack, and in those places unless it is very clear that the change is safe we would likely err on the side of caution.

**Comment by Backs** [comment]
@ajcvickers I checked many places - lot of them use some sort of IReadOnlyCollection, so here, I'm sure, ToList is unnecessary. Sometimes it's list.ToList() calls. Maybe, it's better to split this issue to small tasks like "remove ToList in method A". What do you think?

**Comment by ajcvickers** [comment]
@Backs We discussed this and decided that we will consider PRs to remove ToList but only in places where:
* It can be shown with confidence that there is no functional impact
* It is in a performance critical code path, either in terms of pure performance, or in terms of creating a lot of garbage.

So if you want to pursue this, then smaller PRs with justifications for the points above would probably be the way to go.

**Comment by Backs** [comment]
@ajcvickers ok, I'll split PR to small isolated parts
