### ISSUE TITLE
issues still reported on Codeplex 

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework6#26]
http://entityframework.codeplex.com/workitem/2950 for example..

Not sure of the best approaych to avoid this?

**Comment by divega** [comment]
Unfortunately CodePlex does not support making the issue tracking system read-only, so for some time we will just manually close any incoming bugs and point people here. We didn't want to remove the bugs from there because of its value as a searchable database of known issues, ideas and workarounds.
