### ISSUE TITLE
InvalidOperationException: The property 'xxx' is part of the object's key information and cannot be modified. On Navigation Property change with Composite Key

### ISSUE THREAD

**Issue by sschoeb** [aspnet/EntityFramework6#261]
Looks like the following issue is not entirely resolved:
http://entityframework.codeplex.com/workitem/2628

When using Identity-Columns with a composite key, the newest version of EF (6.2.0-beta2-6050)  does throw the exception:
The property 'TenantId' is part of the object's key information and cannot be modified. 

Sample code that is expected to work:
```
 public class Customer
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(Order = 0)]
        public int Id { get; set; }

        [Key]
        [Column(Order = 1)]
        public int TenantId { get; set; }

        public string Name { get; set; }

        public int? OrderId { get; set; }

        public Order Order { get; set; }
    }

 public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(Order = 0)]
        public int Id { get; set; }

        [Key]
        [Column(Order = 1)]
        public int TenantId { get; set; }

        public string Name { get; set; }
    }

public class Tenant
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Name { get; set; }
    }

 public class TestContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Tenant> Tenants { get; set; }

        public TestContext() : base("name=TestConnString")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Customer>()
                .HasKey(c => new { c.TenantId, c.Id })
                .HasOptional(x => x.Order)
                .WithMany()
                .HasForeignKey(x => new { x.TenantId, x.OrderId });
        }
    }

 class Program
    {
        static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                SeedData(db);

                var customer = db.Customers.First();
                customer.Order = new Order { TenantId = 1 };

                // This line throws the exception
                db.ChangeTracker.DetectChanges();

                Console.WriteLine("When reaching this point, everythign worked fine!");
                Console.ReadLine();
            }
        }

        private static void SeedData(TestContext db)
        {
            var tenant = new Tenant {Name = "First Tenant"};
            db.Tenants.Add(tenant);

            db.Customers.Add(new Customer
            {
                Name = "First customer",
                TenantId = 1
            });

            db.SaveChanges();
        }
    }
```

Here is an updated repo to reproduce the issue:
https://github.com/sschoeb/ef_key_issue_repo

**Comment by ajcvickers** [comment]
@sschoeb That issue is listed as fixed in 6.2, but we have not released 6.2 yet. We are planning to release a beta _very soon now_. Once the beta is out, it would be great if you could test with it and check that the issue you are seeing is fixed.

**Comment by sschoeb** [comment]
You are right. Does that mean, that the current nigthly (which is used in
the repo I provided) does not yet include the fix?

If it does, it is not fixed, as the repo clearly reproduces the issue.

Arthur Vickers <notifications@github.com> schrieb am So., 7. Mai 2017,
22:34:

**Comment by ajcvickers** [comment]
@sschoeb We will look into it again. Didn't realize you were using a nightly build.

**Comment by ajcvickers** [comment]
@sschoeb So the problem here is in the mapping of the FK. This code:
```C#
modelBuilder.Entity<Customer>()
                .HasOptional(x => x.Order)
                .WithMany()
                .HasForeignKey(x => new { x.TenantId, x.OrderId });
```
makes a composite FK with the properties in the order shown--that is TenantId, OrderId. However, the composite PK has these properties in the opposite order, because of the Column(Order = ) annotations. It should be possible to fix this by overriding the order of the PK in the fluent API:
```C#
modelBuilder.Entity<Order>()
    .HasKey(c => new { c.TenantId, c.Id });
```
but it seems that having the column order in the attribute and the order in the fluent API different causes EF to get confused. We will re-triage to decide what to do about this (note--see #110 and #113 as well.) 

For now, either changing the order in the attributes:
```C#
public class Order
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column(Order = 1)]
    public int Id { get; set; }

    [Key]
    [Column(Order = 0)]
    public int TenantId { get; set; }

    public string Name { get; set; }
}
```
or removing the attributes and using the fluent API:
```C#
public class Order
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Key]
    public int TenantId { get; set; }

    public string Name { get; set; }
}

modelBuilder.Entity<Order>()
    .HasKey(c => new { c.TenantId, c.Id });

```
should make this work.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by lanlehoang67** [comment]
sad

**Comment by lanlehoang67** [comment]
is it fixed ?
