### ISSUE TITLE
Unnecessary join when filtering and selecting from/by optional related entity

### ISSUE THREAD

**Issue by kosinsky** [aspnet/EntityFramework6#272]
For model with two entities Product and Category, Product has optional category property. When I’m trying to select products by Category and select properties of the Category. In generated SQL Category tables will be joined twice: one with inner for filtering  and second with outer for select.

  public class Northwind : DbContext
    {

        public Northwind()
            : base("name=Northwind")
        {
            Database.SetInitializer<Northwind>(null);
        }
        public DbSet<Product> Products { get; set; }
    }

    public class Product
    {

        [Key]

        public int ProductId { get; set; }

        public string Name { get; set; }

        public int? CategoryId { get; set;}

        public Category ProductCategory { get; set; }
    }

    public class Category
    {
        [Key]
        public int CategoryId { get; set; }

        public string Name { get; set; }
    }

Query:
            var db = new Northwind();
            var query = db.Products.Where(p => p.ProductCategory.Name == "Bla").Select(p => new { p.ProductId, p.Name, CategoryName = p.ProductCategory.Name } );
            Console.WriteLine(query.ToString());

Generated SQL:
SELECT
    [Extent1].[ProductId] AS [ProductId],
    [Extent1].[Name] AS [Name],
    [Extent3].[Name] AS [Name1]
    FROM   [dbo].[Products] AS [Extent1]
    INNER JOIN [dbo].[Categories] AS [Extent2] ON [Extent1].[CategoryId] = [Extent2].[CategoryId]
    LEFT OUTER JOIN [dbo].[Categories] AS [Extent3] ON [Extent1].[CategoryId] = [Extent3].[CategoryId]
    WHERE N'Bla' = [Extent2].[Name]

Instead of :
SELECT
    [Extent1].[ProductId] AS [ProductId],
    [Extent1].[Name] AS [Name],
    [Extent2].[Name] AS [Name1]
    FROM   [dbo].[Products] AS [Extent1]
    LEFT OUTER JOIN [dbo].[Categories] AS [Extent2] ON [Extent1].[CategoryId] = [Extent2].[CategoryId]
    WHERE N'Bla' = [Extent2].[Name]

Include is affected too. Following query
var query = db.Products.Include("ProductCategory").Where(p => p.ProductCategory.Name == "Bla");
will generate:
SELECT
    [Extent1].[ProductId] AS [ProductId],
    [Extent1].[Name] AS [Name],
    [Extent1].[CategoryId] AS [CategoryId],
    [Extent3].[CategoryId] AS [CategoryId1],
    [Extent3].[Name] AS [Name1]
    FROM   [dbo].[Products] AS [Extent1]
    INNER JOIN [dbo].[Categories] AS [Extent2] ON [Extent1].[CategoryId] = [Extent2].[CategoryId]
    LEFT OUTER JOIN [dbo].[Categories] AS [Extent3] ON [Extent1].[CategoryId] = [Extent3].[CategoryId]
    WHERE N'Bla' = [Extent2].[Name]

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
