### ISSUE TITLE
Consider making the DbQuery.Sql property public

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#282]
The property was added as part of the fix for #73. Since it is private, in debugging windows it is necessary to expand 'Non-public members' before you can see it (this is in addition to having to click on the threads glyph which is also frequently necessary): 

![image](https://cloud.githubusercontent.com/assets/1253414/26339285/ccd9f424-3f3b-11e7-98bc-948b8c01b2a6.png)

**Comment by ajcvickers** [comment]
@divega Based on the testing I did for this in EF Core, if we make it a public property, then it will be evaluated immediately in the debugger window. That's why we have the DebugView property in EF Core--it delays evaluation of this until DebugView is expanded. But maybe "DebugView" isn't any better than "Non-Public members"? Or maybe I am missing something... 😸

**Comment by CZEMacLeod** [comment]
Would using Lazy<string> help here at all? I'm not sure how the debugger works with evaluating and showing lazy members - I think this would also allow easy casting to string in code without much thought if and when it is required?

**Comment by ajcvickers** [comment]
@divega Did some testing and public Sql property will be evaluated when "query" is expanded, not before. Given this, I think the change to make it public is okay.

@CZEMacLeod Lazy in the debugger is a whole other can of worms. :/)

**Comment by divega** [comment]
@ajcvickers cool. Sounds good then.
