### ISSUE TITLE
Generic entities

### ISSUE THREAD

**Issue by matthiasburger** [aspnet/EntityFramework6#284]
In Entity Framework 7 (is it now called "Entity Framework Core"?!) we can have something like this:

    public class GenericEnt<TEntity>:IEntity where TEntity : IEntity
    {
        public int Id{get;set;}
        public TEntity Entity { get; set; }
    }

    public interface IGenericEnt<TEntity> where TEntity:IEntity
    {
        ICollection<GenericEnt<TEntity>> GenericEnts { get; set; }
    }

    public class MyEntity: IEntity, IGenericEnt<MyEntity>
    {
        public int Id {get;set;}
        public string Name {get;set;}
        public ICollection<GenericEnt<MyEntity>> GenericEnts {get;set;}
    }

So we can use generic classes for dependent entities (like e.g. creating recursive entities or history (mutation) entities). The example would build an entity called `MyEntity` and one called e.g. `GenericEnt_MyEntity`. 
In 6.1 this was not supported. Are there plans to support something like this in EF 6?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
