### ISSUE TITLE
datetime2 precision

### ISSUE THREAD

**Issue by daliusd** [aspnet/EntityFramework6#289]
When I create entries using EF6 (6.1.3) having "datetime2(7)" columns then entries are created properly using 7 digits precision. Quering (Selects) using EF6 meanwhile always treat DateTime type as datetime (not as datetime2) and precision drops to 3 digits precision. In result if I have entry with value "2017-05-29T10:10:10.1234567" and try to select something like "datetime2column > dateTimeVar" with same value then "dateTimeVar" in query becomes "datetime" type with value "2017-05-29T10:10:10.123" and my entry satisfies value even though in reality it shouldn't.

SqlQuery that doesn't know anything about datetime precision is using 3 digits precision as well. The only workaround I have found is to convert datetime to string and construct query manually.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by daliusd** [comment]
I have tried to write program that reproduces this issue but it works as intended. I am closing this issue for now until I will find out what's different in my case.

**Comment by daliusd** [comment]
It looks like Future() is the problem. Sample application attached. Application demonstrates problem as well as it randomly can return 1 on query with Future while it should always return 0.

Query without Future():

exec sp_executesql N'SELECT 
    [Extent1].[ItemID] AS [ItemID], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[AddDate] AS [AddDate]
    FROM [dbo].[Items] AS [Extent1]
    WHERE [Extent1].[AddDate] > @p__linq__0',N'@p__linq__0 datetime2(7)',@p__linq__0='2017-08-03 09:08:14.**7308271**'



Query with Future():

SELECT 
    [Extent1].[ItemID] AS [ItemID], 
    [Extent1].[Name] AS [Name], 
    [Extent1].[AddDate] AS [AddDate]
    FROM [dbo].[Items] AS [Extent1]
    WHERE [Extent1].[AddDate] > @f0_p__linq__0;
',N'@f0_p__linq__0 datetime',@f0_p__linq__0='2017-08-03 09:08:14.**730**'


[ConsoleApplication1.zip](https://github.com/aspnet/EntityFramework6/files/1196645/ConsoleApplication1.zip)

**Comment by ajcvickers** [comment]
@daliusd Future() is not part of EF but is instead implemented by EntityFramework.Extensions. As such it would be better to follow up with the authors of EntityFramework.Extensions or with the community in general. If there is an underlying bug in EF, then please provide details and we will investigate more.
