### ISSUE TITLE
powertools build error.

### ISSUE THREAD

**Issue by julianhu1979** [aspnet/EntityFramework6#290]
I am using vs2017 to build the lastest soruce code of powertools. There are some dependenced libraries missed. such as 1)Microsoft Development Environment 8.0 (Version 7.0 Object Model),
                          2)Microsoft Development Environment 8.0,
                          3)Microsoft.VisualStudio.ComponentModelHost,
                          4)Microsoft.VisualStudio.Shell.11.0,
                          5)Microsoft.VisualStudio.Shell.Design

**Comment by ajcvickers** [comment]
@lajones Can you provide any help/info here?

**Comment by lajones** [comment]
@julianhu1979 @ajcvickers For those errors, I would echo @ErikEJ's comment above. It looks like you're missing the VS Extension Development workload. See the selected workload in the VS Installer below.
![170612_vsextensiondevelopmentworkload](https://user-images.githubusercontent.com/1915927/27056792-6d7fe102-4f7e-11e7-9323-cc575f26f589.JPG)

Note: I tried this out myself. With the latest released version of VS (15.2) I am seeing different errors to do with not being able to load `EnvDTE` and `EnvDTE80`. So we need to update the references in PowerTools.csproj to just `Reference` those, rather than using the old `COMReference`. After that the build works as expected. We should keep this open to track that work.

**Comment by ErikEJ** [comment]
I have logged: https://github.com/ErikEJ/EntityFramework6PowerTools/issues/12

**Comment by ErikEJ** [comment]
Close this? https://marketplace.visualstudio.com/items?itemName=ErikEJ.EntityFramework6PowerToolsCommunityEdition is now published

**Comment by divega** [comment]
Per @ErikEJ's comment, we are going to recommend customers to use the Community Edition moving forward.
