### ISSUE TITLE
Distinct for IEnumerable

### ISSUE THREAD

**Issue by Backs** [aspnet/EntityFramework6#294]
I have found strange behavior with Distinct inside Where statement:

    public class DistinctTests : FunctionalTestBase
    {
        [Fact]
        public void Test()
        {
            using (var ctx = new DistinctTestContext())
            {
                var array = new[] { 1, 2, 1 };

                var query = ctx.Numerics.Where(s => array.Distinct().Contains(s.Id));
                Console.WriteLine(query.ToString());
            }
        }

        private class DistinctTestContext : DbContext
        {
            public DbSet<Entity> Numerics { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Entity>();
            }
        }

        public class Entity
        {
            public int Id { get; set; }
            public string Value { get; set; }
        }
    }

Output is:
```
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Value] AS [Value]
    FROM [dbo].[Entities] AS [Extent1]
    WHERE  EXISTS (SELECT 
        1 AS [C1]
        FROM ( SELECT DISTINCT 
            [UnionAll2].[C1] AS [C1]
            FROM  (SELECT 
                1 AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable1]
            UNION ALL
                SELECT 
                2 AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable2]
            UNION ALL
                SELECT 
                1 AS [C1]
                FROM  ( SELECT 1 AS X ) AS [SingleRowTable3]) AS [UnionAll2]
        )  AS [Distinct1]
        WHERE [Distinct1].[C1] = [Extent1].[Id]
    )
```

I think, EF shouldn't convert Distinct staement to SQL code, but just filter values and generate simple code:

```
SELECT 
    [Extent1].[Id] AS [Id], 
    [Extent1].[Value] AS [Value]
    FROM [dbo].[Entities] AS [Extent1]
    WHERE [Extent1].[Id] IN (1, 2)
```

**Comment by CZEMacLeod** [comment]
It also appears that it only returns entities with the ID =1 not 1 or 2.
The inner query
```sql
SELECT 1 AS [C1]
FROM (
	SELECT DISTINCT [UnionAll2].[C1] AS [C1]
	FROM (
		SELECT 1 AS [C1]
		FROM (
			SELECT 1 AS X
			) AS [SingleRowTable1]
		
		UNION ALL
		
		SELECT 2 AS [C1]
		FROM (
			SELECT 1 AS X
			) AS [SingleRowTable2]
		
		UNION ALL
		
		SELECT 1 AS [C1]
		FROM (
			SELECT 1 AS X
			) AS [SingleRowTable3]
		) AS [UnionAll2]
	) AS [Distinct1]
```
Returns 2 records both with C1 = 1
```sql
SELECT [Distinct1].[C1] AS [C1]
FROM (
	SELECT DISTINCT [UnionAll2].[C1] AS [C1]
	FROM (
		SELECT 1 AS [C1]
		UNION ALL
		SELECT 2 AS [C1]
		UNION ALL
		SELECT 1 AS [C1]
		) AS [UnionAll2]
	) AS [Distinct1]
```
Gives the correct output - I don't understand what the 1 as x as singlerowtable bit is about?
Maybe the optimizers make it irrelevant, but the SQL seems much more complicated that it needs to be.
Also wouldn't
```sql
SELECT [Extent1].[Id] AS [Id]
	,[Extent1].[Value] AS [Value]
FROM [dbo].[Entities] AS [Extent1]
WHERE [Extent1].[Id] IN (
		SELECT DISTINCT [UnionAll2].[C1] AS [C1]
		FROM (
			SELECT 1 AS [C1]
			
			UNION ALL
			
			SELECT 2 AS [C1]
			
			UNION ALL
			
			SELECT 1 AS [C1]
			) AS [UnionAll2]
		)
```
make more sense?

Personally I avoid this by generating a list of IDs outside the lambda and 'caching' it, rather then evaluating the list inside. I believe this is good practise with normal LINQ as it prevents the evaluation occurring for each item.

```csharp
    public void Test()
    {
        using (var ctx = new DistinctTestContext())
        {
            var array = new[] { 1, 2, 1 };
            var ids = array.Distinct().ToArray();
            var query = ctx.Numerics.Where(s => ids.Contains(s.Id));
            Console.WriteLine(query.ToString());
        }
    }
```

**Comment by Backs** [comment]
> It also appears that it only returns entities with the ID =1 not 1 or 2.
No, result is correct, it will return data for 1 or 2. But SQL is too complicated.

**Comment by CZEMacLeod** [comment]
Ah - yes. Re-read the query. It works because it is in the WHERE EXISTS bit and the 1 is used as the detection not the value. But the SQL is way too complicated.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
