### ISSUE TITLE
ProviderManifestToken uses version from SQL server instead of from database

### ISSUE THREAD

**Issue by davidliang2008** [aspnet/EntityFramework6#295]
Issue: code developed on a SQL 2005 database using DATETIME will result in errors of
`The version of SQL server in use does not support datatype 'datetime2'`

See [https://stackoverflow.com/questions/316422/using-sql-server-2008-and-sql-server-2005-and-date-time](https://stackoverflow.com/questions/316422/using-sql-server-2008-and-sql-server-2005-and-date-time).

The issue is that Entity Framework examines the SQL version of the server
`SELECT @@VERSION AS [@@Version], serverproperty('ProductVersion') AS ProductVersion`

`
@@Version        ProductVersion
Microsoft SQL Server 2012 (SP3-GDR) (KB3194721) - 11.0.6248.0 (X64)
                Sep 23 2016 15:49:43
                11.0.6248.0
`

Instead of the version of the database itself:
`SELECT name AS [DB Name], compatibility_level AS [Compatibility Level] FROM master.sys.databases;`

In my case, 110 vs 90.

As a result, Entity Framework will try to use DATETIME2 even though that is not valid for SQL 2005 database.

The edmx file will have something like
`
    <Schema 
        Namespace="dbNameModel.Store" 
        Provider="System.Data.SqlClient" 
        ProviderManifestToken="2012" 
        Alias="Self" 
        xmlns:store="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator" 
        xmlns:customannotation="http://schemas.microsoft.com/ado/2013/11/edm/customannotation" 
        xmlns="http://schemas.microsoft.com/ado/2009/11/edm/ssdl"
    >
`

instead of 

`<Schema Namespace="dbNameModel.Store" Provider="System.Data.SqlClient" ProviderManifestToken="2005" Alias="Self" xmlns:store="http://schemas.microsoft.com/ado/2007/12/edm/EntityStoreSchemaGenerator" xmlns:customannotation="http://schemas.microsoft.com/ado/2013/11/edm/customannotation" xmlns="http://schemas.microsoft.com/ado/2009/11/edm/ssdl">`

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Note that you can manually edit the manifest token in the EDMX file (for Database First) or use something like https://msdn.microsoft.com/en-us/library/system.data.entity.dbconfiguration.setmanifesttokenresolver(v=vs.113).aspx#M:System.Data.Entity.DbConfiguration.SetManifestTokenResolver(System.Data.Entity.Infrastructure.IManifestTokenResolver) for Code First.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
