### ISSUE TITLE
Idea: componentized designer wizard 

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#302]
Currently when you choose to add an "ADO.NET Entity Data Model" to a project we offer a fixed set of options: 

![image](https://user-images.githubusercontent.com/1253414/27255659-af446270-5357-11e7-814a-86a8063bc271.png)

Considering:
 
- recent feedback indicating that some customers used to EF6 don't know how to start using EF Core 
- the existence of third party utilities that allow creating EF models such as the [@sjh37's Reverse POCO generator](https://marketplace.visualstudio.com/items?itemName=SimonHughes.EntityFrameworkReversePOCOGenerator) or @ErikEJ's  [SQLite Toolbox](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox), and also commercial offerings such as https://www.llblgen.com/ and https://www.devart.com/entitydeveloper/,
- feedback about having custom items representing pre-made models, like https://data.uservoice.com/forums/72025--closed-entity-framework-core-feature-suggestions/suggestions/7576092-enable-extending-entity-framework-model-wizard-to 

we are starting to think about:

- Turning the first page of the wizard into an extensible launch pad for our own and third party extensions
- Adding default EF Core options there
- Possibly standardizing on ways to differentiate between options that 
  - Create empty models vs. models from existing databases
  - Support Entity Framework 6 or below vs. Entity Framework Core
- Possibly changing the name of "ADO.NET Entity Data Model" to something more accurate, e.g. "Entity Framework model".

**Comment by ErikEJ** [comment]
@sjh37 !

**Comment by xperiandri** [comment]
Could you create a new wizard in WPF by reusing some available options? This Windows Forms dialog is extremely outdated.

**Comment by divega** [comment]
@xperiandri we would consider that if there is a lot of value in it, otherwise we will go with minimal changes. Could you explain what the advantages would be?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
