### ISSUE TITLE
Consider replacing GetTempFileName with GetTempPath and GetRandomFileName

### ISSUE THREAD

**Issue by jbagga** [aspnet/EntityFramework6#306]
Consider removing uses of `GetTempFileName` as

> The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files.

P0:

- DbContextPackage
- updatefromdatabaseengine

P1:

- ConfigurationFileUpdater
- FileUtils
- IOHelper
- ProjectExtensions
- AppConfigureReaderTests
- CodeFirstModelGeneratorTests
- ConfigurationFileUpdaterTests
- ConnectionFactoryConfigTests
- DatabaseLoggerTests
- EdmUtilsTests
- EdxmUtilityTests
- EntityFrameworkSectionTests
- TestBase

See aspnet/Coherence-Signed#510 for more information.

cc @Eilon

**Comment by smitpatel** [comment]
Why this is in EF6 repo? Coherence-Signed doesn't even build EF6

**Comment by jbagga** [comment]
The issue just has more details. The issue is about the instances of `GetTempFileName` across aspnet

**Comment by ajcvickers** [comment]
We don't believe this should be done for EF6. There is no Linux support anyway, and the new replacement code does not seem to be as robust/good as the original code.

**Comment by Eilon** [comment]
BTW this isn't related to Linux or xplat. I think it's entirely a Windows-only problem and can make apps unreliable because GetTempFile is not a reliable API. Your call, though.

**Comment by ajcvickers** [comment]
Re-opening since @Eilon indicates this is a Windows issue.

**Comment by ajcvickers** [comment]
Discussed again in triage. We haven't seen any customers reporting this issue, so we're not going to do anything immediately to fix it, especially since the use is in design-time code, meaning that if someone did hit it, then they would be able to go delete files on their machine. Beyond that, we will follow up on the idea that this API can basically never be used and figure out if it will ever get fixed and, if not, why it is not marked as obsolete.
