### ISSUE TITLE
InvalidOperationException: No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SqlClient'.

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#311]
_From @stanuku on July 8, 2017 6:6_

Hello - I'm getting this runtime exception.

My solution details:

**Target Framework = .NET 4.6.1** 

- VS 2017 15.2 (26430.120
- A class library project (repositories library) using DbContext (using Entity Framework 6.3, **not** EF Core)
- ASP.NET Core 1.1 API project referencing the repositories project.
- Running any query using DbContext throws this exception.

Adding the ```<entityFramework>``` in the App.config of the API project doesn't help. **I suspect that the build is not copying EntityFramework.SqlServer.dll to the API project's bin folder.**

Adding Entity Framework package to the API project directly does copy the EntityFramework.SqlServer.dll to the bin folder during build. However, I don't prefer to do that. Rather I would like to maintain the indirection through the repository project.

Any suggestions? (again, I'm not using EF Core, can't take chances in this critical project).

Thanks

_Copied from original issue: aspnet/EntityFramework#9120_

**Comment by ajcvickers** [comment]
See https://entityframework.codeplex.com/workitem/2352

**Comment by ajcvickers** [comment]
@stanuku See the CodePlex issue above for information about making sure the assembly gets deployed. In addition to this, you'll need to make sure that any necessary config file changes are made. We do the best we can within the NuGet environment to ensure that these changes get made for you, but depending on where and how you have NuGet install the package you may need to make some changes manually. Closing this, as we don't think there is anything actionable on the EF Side.

**Comment by Nekromancer** [comment]
I'm having the same issue and provided link doesn't work anymore. Can you point me to the solution?

**Comment by ajcvickers** [comment]
Info from the CodePlex issue:

There's an issue which a number of people have reported when using EF 6 with Code First around the EntityFramework.SqlServer provider (or another provider they are using) not being copied locally. This leads to the following error:

> System.InvalidOperationException: The Entity Framework provider type 'System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer' registered in the application config file for the ADO.NET provider with invariant name 'System.Data.SqlClient' could not be loaded. Make sure that the assembly-qualified name is used and that the assembly is available to the running application. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

This only occurs when the EntityFramework NuGet package is not installed in the start-up project (i.e. it is only installed in a class library etc.)

This issue isn't specific to Entity Framework, but is a side effect of how MSBuild works out which assemblies need to be deployed. The issue occurs because there is no code in the application that explicitly references types in EntityFramework.SqlServer.dll (or relevant provider assembly) since EF will load the assembly at runtime based on info in the App/Web.config file. As a result, MSBuild does not detect that the assembly is needed and will not copy it to the output directory.

There are workarounds to solve this issue:
* Install NuGet package in start up project. Simply installing the NuGet package that contains the provider in the start up application is enough to resolve this issue. In the case of SqlServer, this means installing the EntityFramework NuGet package in your start up project. 
* Add code to reference types from the provider assembly. You can add a line of code that references a type in the provider assembly. This line of code won't actually do anything and can be placed anywhere in your application: `var ensureDLLIsCopied = System.Data.Entity.SqlServer.SqlProviderServices.Instance;`

Why isn't EF fixing this issue? This issue isn't specific to EF and is a general MSBuild issue. That said, if there was a reasonable way for us to resolve the issue we would. The easiest way would be to have code in EntityFramework.dll that references EntityFramework.SqlServer.dll, but this isn't possible because the SqlServer assembly needs to reference the main EF assembly. Given that there is no clean way for us to resolve the issue, and that there are simple workarounds, we are not going to try and fix it.
