### ISSUE TITLE
Setting property on Proxy and then loading original value somewhere else, restores orignal value-

### ISSUE THREAD

**Issue by morSchmidt** [aspnet/EntityFramework6#312]
Given an Entity with a referenced entity and a list, 
1. Loading the entity without its referenced entity (resulting in an lazy proxy)
2. Setting the referenced entity property to another entity loaded from the database
3. Loading the original referenced entity from the database will override the assignment that was issued in step 2.

This issue does not appear if the parent entity does not have a list.
I have created a test project which does an assert which i do not think should fail, meaning the test should pass.

[EntityFrameworkProxyIssue.zip](https://github.com/aspnet/EntityFramework6/files/1133678/EntityFrameworkProxyIssue.zip)

I have checked the newest 6.2.0 build and the issue is still present.

**Comment by ajcvickers** [comment]
@morSchmidt Sorry for the slow response. The problem here is that adding an `IList<>` navigation property makes it impossible for EF to create a change-tracking proxy for the type. If the navigation is instead created as an `ICollection<>`, then the issue no long repros:
```C#
public virtual ICollection<IngredientBarcode> Barcodes { get; set; } = new List<IngredientBarcode>();
```
The reason this happens when the entity is not a change-tracking proxies is that the change `ingredient.DeliveredUnit = boxUnit;` is not seen by EF until DetectChanges is called, and executing a query does not automatically call DetectChanges.

A couple of links that might help:
* https://blog.oneunicorn.com/2012/03/10/secrets-of-detectchanges-part-1-what-does-detectchanges-do/
* https://blog.oneunicorn.com/2011/12/05/entity-types-supported-by-the-entity-framework/
