### ISSUE TITLE
Power Tools View commands don't work if startup project config file uses external files with configSource attribute

### ISSUE THREAD

**Issue by CZEMacLeod** [aspnet/EntityFramework6#314]
Using a Power Tool command such as View EDM (read-only) fails as it copies the web.config from the startup project to my temp folder but does not copy or fixup the paths for sections referred to in configSource lines.
```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to open configSource file 'App_Data\connectionStrings.config'. (C:\Users\xxxx.xxxx\AppData\Local\Temp\tmpF9AD.tmp line 19)
---------------------------
OK   
---------------------------
```
```
  <connectionStrings configSource="App_Data\connectionStrings.config" />
```
I think the tool should either inline these files/sections, or copy the files with temp names and fix-up the paths.
Note a similar issue may occur with appSettings although in this case the section is merged rather than replaced.
```
  <appSettings file="App_Data\appSettings.config">
    <add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="aspnet:MaxHttpCollectionKeys" value="2000" />
  </appSettings>
```

**Comment by CZEMacLeod** [comment]
For reference - I think this should be part of the FixUpConfig method in EntityFramework6/src/PowerTools/DbContextPackage.cs

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
