### ISSUE TITLE
Entity splitting with left join

### ISSUE THREAD

**Issue by bdebaere** [aspnet/EntityFramework6#315]
I am currently working on a business project with extremely little control over the database structure. The database has the following tables: Item, ItemProperties, ItemFlags, et cetera.

When there are no extra properties no record is made in the ItemProperties table instead of a record with all NULLs. I would very much like to use entity splitting so my output is a nice clean class: Item. This poses a problem as Entity Framework uses INNER JOIN when using entity splitting.

The SQL output is also not what I would expect. I would expect the first table to be mapped to be the first in the query. Instead the other table is queried first, which poses a second problem because there is actually no record in this table for that id.
SELECT 
    [Extent1].[ItemId] AS [ItemId], 
    [Extent1].[PropertyOfItemProperties1] AS [PropertyOfItemProperties1], 
    [Extent2].[PropertyOfItem1] AS [PropertyOfItem1]
    ...
    FROM  [dbo].[ItemProperties] AS [Extent1]
    INNER JOIN [dbo].[Item] AS [Extent2] ON [Extent1].[ItemId] = [Extent2].[ItemId]
    WHERE  [Extent1].[ItemId] =  @p__linq__0

I've read this is by design, so I would probably be wasting my time asking for a change? Instead I will ask: is there a workaround for these two problems?

**Comment by divega** [comment]
@bdebaere we discussed this and we believe that

1. Yes, it is by design, and changing the assumption that the dependent row always exists would involve prohibitively expensive changes. E.g. we would need to track whether the row exists in the database to decide whether and update on the entity level should generate an INSERT or an UPDATE operation against the table.

2. We think that the simplest workaround would be perform the entity splitting by hand in your code. This means:

1. Have two separate entities mapped to Item and ItemProperties tables and a navigation property
2. Create unmapped properties on the .NET type for Item that delegate to the related entity
3. Make sure you configure the relationship as 1:0..1

E.g. the Item entity would look somewhat like this:

``` C#
public class Item
{
    int Id { get; set; }
    string LocalProperty { get; set; }
    string ItemProperties Properties {get; set; }
    [NotMapped]
    string DelegatedProperty 
    {
        get 
        {
            return Properties?.DelegatedProperty;
        }
        set
        {
            if (value != null && Properties == null)
            {
                Properties = new ItemProperties();
            }
            Properties.DelegatedProperty = value;
        }
    }
}
```

**Comment by bdebaere** [comment]
@divega Thank you for your time. This does not seem to give the output that I want. The JSON output lacks the DrawingId, even for Items which clearly have one. Did I forget something? What am I missing? 

Also, as far as I'm aware, this will make 3 extra database queries when I have 3 mapped entities? If this is correct then this is a method I would like to avoid and hope that you have another suggestion?

This is my code (the setter or getter never get executed):
```
public class Item
{
       [NotMapped]
        public int? DrawingId {
            get
            {
                return ItemDrawing?.DrawingId;
            }
            set
            {
                if (value == null)
                    return;

                if (ItemDrawing == null)
                    ItemDrawing = new ItemDrawing();

                ItemDrawing.DrawingId = value.Value;
            }
        }
        public virtual ItemDrawing ItemDrawing { get; set; }
}
```

```
dbModelBuilder.Entity<Item>()
                .HasOptional(property => property.ItemDrawing)
                .WithRequired(property => property.Item)
                .WillCascadeOnDelete();

```
