### ISSUE TITLE
Update-Database -Rollback-Last-Migration

### ISSUE THREAD

**Issue by tlk** [aspnet/EntityFramework6#321]
This is a suggestion to extend the Update-Database command to be able to rollback the last applied migration.

I believe that a common work pattern for a developer using entity framework is to scaffold a new migration, apply it, realize that something needs to be changed, rollback the migration, re-scaffold, and re-apply the migration. See https://stackoverflow.com/questions/11904571/ef-migrations-rollback-last-applied-migration which as of today has 244 upvotes.

Today, a developer will have to do something like this:
```powershell
Update-Database                            # Update the database to the latest migration
Add-Migration Foo                          # Scaffold a new migration named "Foo"
Update-Database                            # Update the database to the latest migration (Foo)
Update-Database -Target-Migration Bar     # <--- PAIN POINT
Add-Migration -Force -Name Foo             # Scaffold (overwrite) any existing migration named "Foo"
Update-Database                            # Update the database to the latest migration (Foo)
```

As illustrated above, a developer will have to manually look up the name of the latest applied migration "Bar".

It would be easier if the "Update-Database" tool had builtin support for this common operation, so the developer does not have to manually look up the name of the latest applied migration.

With a "Update-Database -Rollback-Last-Migration" command, a developer would be to perform the following sequence of operations:
```powershell
Update-Database                            # Update the database to the latest migration
Add-Migration Foo                          # Scaffold a new migration named "Foo"
Update-Database                            # Update the database to the latest migration (Foo)
Update-Database -Rollback-Last-Migration   # Rollback the latest applied migration (Foo)
Add-Migration -Force -Name Foo             # Scaffold (overwrite) any existing migration named "Foo"
Update-Database                            # Update the database to the latest migration (Foo)
```

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
