### ISSUE TITLE
Local property performance

### ISSUE THREAD

**Issue by kukadlo** [aspnet/EntityFramework6#330]
When there is a lot of records in the database table, the access to DbSet's Local property (EF6) takes a very long time. The same property access is very quick in the EF Core. Does it mean there is some different programming approach to this property ? Cannot be the EF6 Local property rewritten by the same way to be quick too ?

**Comment by divega** [comment]
@kukadlo the implementation is quite different for `Local` between EF6 and EF Core. E.g. the way I understand it, in EF6, `Local` contains a copy of the contents of the change tracker that is kept in sync, vs. in EF Core it functions more like a view over the data in the change tracker, without copying the references. 

I believe changing the implementation in EF6 could be a bit expensive and would require breaking changes for it to function like in EF Core, but I will let @ajcvickers provide more details.

**Comment by ajcvickers** [comment]
@divega is correct. We won't be changing Local on EF6 because it would be a breaking change in several ways. However, it might be possible to create an extension method for EF6 that operates as an observable view over the state manager, just like in EF Core. This is not something we are going to work on, but if you decide to give it a try then I would be interested to hear how it goes.
