### ISSUE TITLE
Putting orderby before projection causes EF to generate exponential unused OUTER APPLY, OUTER JOIN, and CROSS JOIN in SQL

### ISSUE THREAD

**Issue by ykosbie** [aspnet/EntityFramework6#353]
Originally discovered because the bug caused an OutOfMemoryException in my query while it was trying to create the query plan.  See original q here: https://stackoverflow.com/q/46144625/794234.  This issue is also posted as a Q on SO: https://stackoverflow.com/q/46151694/794234.

**tl;dr;** Putting `orderby contact.Property` before my projection (`let defaultAddress = contact.Addresses...`) creates an exponentially more complex SQL statement and sometimes causes an OutOfMemoryException.

Question

I have a simple data model for storing contact information

    public class Contact {
        public int ContactID { get; set; }

        public virtual ICollection<Address> Addresses { get; set; }
        //etc
    }

    public class Address {
        public int AddressID { get; set; }

        public int ContactID { get; set; }
        public virtual Contact Contact { get; set; }
        //etc
    }

I want to project that into a flat model and sort the results, for example

	from c in Contacts
	let a = c.Addresses.FirstOrDefault()
    orderby c.DOB
	select new {
		ContactID = c.ContactID,
		AddressID = a.AddressID
	}

That generates straightforward SQL

	SELECT 
	    [Project2].[ContactID] AS [ContactID], 
	    [Project2].[C1] AS [C1]
	    FROM ( SELECT 
	        [Extent1].[ContactID] AS [ContactID], 
	        [Extent1].[DOB] AS [DOB], 
	        (SELECT TOP (1) 
	            [Extent2].[AddressID] AS [AddressID]
	            FROM [dbo].[Addresses] AS [Extent2]
	            WHERE [Extent1].[ContactID] = [Extent2].[ContactID]) AS [C1]
	        FROM [dbo].[Contacts] AS [Extent1]
	    )  AS [Project2]
	    ORDER BY [Project2].[DOB] ASC

If I switch the order of the `orderby c.DOB` to be before `let a = ...`, EF adds an entire extra `OUTER APPLY` statement to the generated SQL.

	SELECT 
	    [Project2].[ContactID] AS [ContactID], 
	    [Project2].[C1] AS [C1]
	    FROM ( SELECT 
	        [Extent1].[ContactID] AS [ContactID], 
	        [Extent1].[DOB] AS [DOB], 
	        (SELECT TOP (1) 
	            [Extent3].[AddressID] AS [AddressID]
	            FROM [dbo].[Addresses] AS [Extent3]
	            WHERE [Extent1].[ContactID] = [Extent3].[ContactID]) AS [C1]
	        FROM  [dbo].[Contacts] AS [Extent1]
	        OUTER APPLY  (SELECT TOP (1) [Extent2].[AddressID] AS [AddressID]
	            FROM [dbo].[Addresses] AS [Extent2]
	            WHERE [Extent1].[ContactID] = [Extent2].[ContactID] ) AS [Limit1]
	    )  AS [Project2]
	    ORDER BY [Project2].[DOB] ASC

The query gets significantly more complicated and has *exponentially* more unused OUTER APPLYs, LEFT JOINs and CROSS JOINs if I add more collection properties to my projection or if I add a filter to the collections.  If the query is has enough flat properties putting the orderby in the wrong place will cause an OutOfMemoryException while trying to build a query plan for the massive SQL that gets generated!

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
