### ISSUE TITLE
primary key naming convention

### ISSUE THREAD

**Issue by d4e666** [aspnet/EntityFramework6#38]
Is there a way to insert a PK naming convention since the default gives issues when the tablename is prefixed with the tablespace name e.g. dbo.SomeTableName.

I use MS Access as a frontend during development (just because it's easy to validate data and set up lookup columns.)

This gives errors due to the fact that the dbo part is also used as PK namig convention. Why not replace this kind of "special" characters by something else like underscore. This should make everybody happy. or atleast  make this type of crucial functions virtual for user extensibility.

**Comment by divega** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).
