### ISSUE TITLE
ColumnAttributeConvention behaves inconsistent when used with namespaces only

### ISSUE THREAD

**Issue by Wayofthesin** [aspnet/EntityFramework6#385]
I have been just looking around the code when I spot this in ColumnAttributeConvention.Apply:

```csharp
if (!string.IsNullOrWhiteSpace(attribute.Name))
{
    configuration.HasColumnName(attribute.Name);
}
```

It means that all following cases are equal

```csharp
    [Column]
    public string Nice;

    [Column("")]
    public string Foo {get; set;}

    [Column("    ")]
    public string Bar {get; set;}

    [Column("\n \t  ")]
    public string Baz {get; set;}
```
Personally I would wonder about sanity of anyone who would try to use any of above examples - except obviously the first one but code should be consistent. What if in terms of automatic refactoring some name has been stripped (look for occurences in comments in string from Resharper)? The error would not be detected until the column is actually used (what in real world may be in production).

It should throw even whenever user specified empty string as a name (empty string is still a string!) but that one I should defer to the next Major release due to possibility of some people using syntax:

```csharp
    [Column("", TypeName="nvarchar(666)")]
    public string VeryUglySyntax {get; set;}
```

It does the same for other TypeName in column attribute and very likely in other attributes too.

P.S.: Just to explain the inconsistent in title:

```csharp
[Column(" ")]
public string PropertyNameWillBeColumnName;

[Column("[ ]")]
public string SingleSpaceWillBeColumnName;

[Column("asd")]
public string asdWillBeColumnName;

[Column("[asd]")
public string asdWillBeColumnName;
```

**Comment by Wayofthesin** [comment]
I have just spotted that there is

```csharp
Check.NotEmpty(name, "name");
```

In ColumnAttribute constructor. In such case error will be thrown from Attribute convention but the ColumnAttributeConvention should not accept any other value that null or non-empty string (should throw if value is empty string or contains whitespaces). 

That checks the priority of the issue to code quality.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
