### ISSUE TITLE
Support for UNIQUE column constraints for database first development

### ISSUE THREAD

**Issue by shkleinik** [aspnet/EntityFramework6#400]
It would be handy to have out of the box support for unique column constraints.

As of now(I'm using EF 6.2.0 with Visual Studio Enterprise 2017 v15.4.4) EF ignores UNIQUE column constraints when I'm importing my schema from the database:
1. Open *.edmx diagram file
2. Right click -> Update Model from Database

There is also no way to set UNIQUE constraint from the Model Diagram.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
