### ISSUE TITLE
Suggestion: give better error message on SaveChanges method

### ISSUE THREAD

**Issue by YuichiNukiyama** [aspnet/EntityFramework6#426]
### Code
**table**
```sql
CREATE TABLE [dbo].[Department](
    [IntPK] [int] PRIMARY KEY,
    [DepartmentName] [nvarchar](50) NOT NULL
) ON [PRIMARY]
```

**Model class**
```C#
[Table("Department")]
public class Depertment {
  [Key]   // Key annotation without DatabaseGenerated option
  public int IntPK {get; set;}
  public string DepartmentName {get; set;}
}
```

### Description
Primary key coloumn isn't **identity** and Key annotation **without DatabaseGenerated option**.
So, When I will call SaveChanges method, exeception will be thrown.

But It is difficult to understand the error message
when inserting an int type primary key column. 
Please give better error message on SaveChanges method.

### Expected behavior
I want a message that the DatabaseGenerated option should be changed.

### Actual behavior
"Can not insert value NULL in column 'IntPK ' of table 'DBName.dbo.Depertment' This column does not allow NULL values INSERT fails. The statement has been terminated. "
(I can't find original message. So, I transrate message Japanese to English)

**Comment by ajcvickers** [comment]
@YuichiNukiyama There are a few problems with doing this:
* Understanding from the error that this was really what the application intended is difficult--the same kind of exception can happen for multiple reasons
* The fix is not necessarily the same depending on why the error is happening, so suggesting to use DatabaseGenerated is not necessarily the correct thing to do.
* Doing any of this requires provider-specific interception of database exceptions, which is something that adds complexity and generally has no value.

For these reasons, this is something we are not planning to do in either EF6 or EF Core.
