### ISSUE TITLE
Complex objects cannot be referenced multiple times by the same entity.

### ISSUE THREAD

**Issue by fgarciachipi** [aspnet/EntityFramework6#437]
`The entity of type 'X' references the same complex object of type 'Y' more than once. Complex objects cannot be referenced multiple times by the same entity.`

I have an **address** (complex type) and a **customer** (entity) which has two addresses. My address has a property **NullInstance** that returns a null instance representation of an address using singleton that is why I am getting the error: the customer is created without addresses, both fields have the **NullInstance** of address. I know that if I remove the singleton pattern everything works fine but I would like to know where is the limitation to find the best solution.

I am using EF 6.1.3

**Comment by CZEMacLeod** [comment]
I had some problems in this area when I first started using complex types. I eventually came to the conclusion that you have to think of them (and the containing class) like structures rather than classes.

e.g.
```
    public struct Address
    {
        string Line1;
        string Line2;
        string PostCode;
    }

    public struct Customer
    {
        int Id;
        string Name;
        Address ShippingAddress;
        Address BillingAddress;
    }
```
This is why you have to assign new objects to the address fields in the constructor.
Basically EF is 'flattening' the fields from Address into Customer so it can persist to and from the database.

If you loaded a customer, and both addresses pointed to the same object, then when loading dbo.Customers.BillingAddress_Line1 it would overwrite the ShippingAddress.Line1. Or if you updated one of the billing fields it would update the shipping field.

Also this effectively means the Address objects cannot be null, even if the 'fields' in them can be.

I suggest removing the singleton approach and creating a new empty address object instead and adding an IsNull or similar function to the address object rather than specifically checking for the NullInstance as you defined before.

I have largely stopped using complex types myself and in this case would store all addresses in a separate table and store the ID of the address or NULL - this way you could easily use EF to check for customers without a billing address and have that execute at the database without materializing all the records.

Hope this helps!

**Comment by CADbloke** [comment]
Not a fix but one way to use complex types with EF is to serialize / deserialize them into a string column. See https://stackoverflow.com/a/37207034/492 I'm doing it with EF6 & SQLite and it works fine.

**Comment by ajcvickers** [comment]
@fgarciachipi It's been quite a while since I worked on that code, but to answer your question as best I can I believe it is because the object reference is used as a key in some of the change tracking structures and if the same reference is used for two different parts of the model then things get confused. This is in turn because complex objects are not inherently immutable, so even if you are using them as immutable objects, EF is still treating them as if they are not.

**Comment by fgarciachipi** [comment]
Thank you @ajcvickers for your explanation. From my point of view removing the singleton pattern is the best solution. Thank you @CZEMacLeod and @CADbloke for your comments.
