### ISSUE TITLE
Grouping by primary key of a left-joined entity in Entity Framework causes exception

### ISSUE THREAD

**Issue by khodaie** [aspnet/EntityFramework6#439]
I have a simple model with two entities:

```C#
    public class Product
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(150)] public string Name { get; set; }
    }

    public class Order
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public decimal? Amount { get; set; }

        public int? ProductId { get; set; }

        [ForeignKey(nameof(ProductId))] public Product Product { get; set; }
    }

    public class OrderContext : DbContext
    {
        public DbSet<Product> Products { get; set; }

        public DbSet<Order> Orders { get; set; }
    }
```
As you see, There is a nullable foreign key between the `Order` and `Product`. 
I initialized the DB with these records:
```C#
    using (var db = new OrderContext())
            {
                var p = new Product {Name = "Test"};
                db.Products.Add(p);

                db.Orders.Add(new Order {Product = p, Amount = 1});
                db.Orders.Add(new Order {ProductId = null, Amount = 2});

                db.SaveChanges();
            }
```

When I execute the following query, an `InvalidOperationException` is raised:

```C#
    var result = db.Orders.GroupBy(x => x.Product.Id).ToArray();
```

The exception message is:

> System.InvalidOperationException: The cast to value type 'System.Int32' failed because the materialized value is null. Either the result type's generic parameter or the query must use a nullable type.

**Comment by ajcvickers** [comment]
@khodaie What version of EF or EF Core are you using?

**Comment by khodaie** [comment]
@ajcvickers EF 6.2

**Comment by ajcvickers** [comment]
Note from triage: investigate if null compensation in the supplied LINQ query can handle this.

**Comment by ajcvickers** [comment]
@khodaie It looks like EF6 is not automatically doing null compensation here, but the query worked for me when it was added manually:
```C#
context.Orders.GroupBy(x => x.Product != null ? (int?)x.Product.Id : null).ToArray();
```

**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
