### ISSUE TITLE
Debug/Step into Lazy loading

### ISSUE THREAD

**Issue by luizfbicalho** [aspnet/EntityFramework6#441]
Is there a way to debug and step into de lazy loading code?

I have a problem in EF that I need to get the lazy loaded property before I set the value on the property, because if I only set the value and update, the model is saved as if I didn't set the value.
Example:

`model.Child = ChildRepository.Find(999); // doesn't load value 999
`

And this example:

`var child = model.Child;`
`model.Child = ChildRepository.Find(999); //load value 999
`

I can't reproduce this in a smaller example, so i'm trying to debug and see what's the problem, 
Is there a way do debug, or at least to see the code?

Thanks

**Comment by ajcvickers** [comment]
@luizfbicalho The code above does not seem to use lazy loading--if you're having trouble debugging into your repository code I would follow up with the Visual Studio team. With regard to the lazy loading proxies themselves, I don't believe it is possible to debug into them because they are dynamically generated IL.

**Comment by luizfbicalho** [comment]
@ajcvickers I just put one example to show my lazy loading problem.

Let me explain better:
I have this:

    [Table("Child")]
    public class Child
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual int Id { get; set; }
        public virtual string Desc { get; set; }
    }
    [Table("Parent")]
    public class Parent
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual int Id { get; set; }

        public virtual string Desc { get; set; }
        [Required]

        public virtual Child Child { get; set; }
    }

the property Child in the Parent class can be lazy loaded.

In my big model I have cases that if I set the value of the child property in the Parent class like this example:

```
var parent = GetParent();
parent.Child = GetChild();
```

the property doesn't change, and I have to do this:

```
var parent = GetParent();
var x = parent.Child;
parent.Child = GetChild();
```

I wanted to see what is happening inside the get and set method inside the Child property to see why this is happening, but I coudn't reproduce this in a small test to send to you.

If I do this

```
var parent = GetParent();
var y = GetChild();
parent.Child = y
var x = parent.Child;
//y!=x 
```
and that's what I want to see why.

Hope I could make it more clear to you.

**Comment by ajcvickers** [comment]
@luizfbicalho Without a full repro its hard to say what is happening. With regard to debugging, I don't think you'll be able to debug into the proxies because they are generated IL.

**Comment by luizfbicalho** [comment]
@ajcvickers Is there a template code that I can dig into?
Is there any post os document showing how the lazy loading work?
I want to dig deeper into this, just could use some guidance.

thanks in advance

**Comment by ajcvickers** [comment]
@luizfbicalho It looks like from your code you are probably using change-tracking proxies, rather than lazy loading proxies. Here's a blog post I wrote from some time ago that describes the different proxy types:
https://blog.oneunicorn.com/2011/12/05/entity-types-supported-by-the-entity-framework/

Here's the doc link for proxies and lazy-loading:
https://msdn.microsoft.com/en-us/library/jj592886(v=vs.113).aspx
https://msdn.microsoft.com/en-us/library/jj574232(v=vs.113).aspx

To dig more into the implementation, here are links to the lazy-loading proxy source and the change-tracking proxy source:
https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Core/Objects/Internal/LazyLoadImplementor.cs
https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/Core/Objects/Internal/IPOCOImplementor.cs

I'm not aware of any in-depth articles on the implementation--probably your best bet if you want to get deep into it is to use the source code.
