### ISSUE TITLE
Prevent entities from being loaded

### ISSUE THREAD

**Issue by samiraguiar** [aspnet/EntityFramework6#447]
We have a scenario where certain entities of different types should be excluded depending on an inherited property that some of them have.
Currently we recursively remove those entities from the fetched collection, but this has led to performance issues (we go from the root to all the entities below it) with complex objects.
This, however, is only needed in certain scenarios, not for all queries.

Is there a better way to prevent certain entities from being loaded by checking some of their properties? Maybe when materializing them we could intercept this and don't add them at all.

**Comment by ajcvickers** [comment]
@samiraguiar It sounds like you are referring to query filters. These are [now supported in EF Core](https://github.com/aspnet/EntityFrameworkCore/issues/5774). However, this issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
