### ISSUE TITLE
EF6+ changes to enable more precise logging of queries for supportability.

### ISSUE THREAD

**Issue by brebor** [aspnet/EntityFramework6#448]
There are now three Caller Information attributes that you can add as decorations to your methods as discussed here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/caller-information. By using Caller Info attributes, you can obtain information about the caller to a method. You can obtain file path of the source code, the line number in the source code, and the member name of the caller. This information is helpful for tracing, debugging, and creating diagnostic tools.

I have downloaded the EF source and modified it to use the Caller Info Attributes. I modified the code to output the logging information as JSON that can be read from another tool I created that gives the user an idea where each query was created.

These are the changes that were done to the EF code…
I made two new classes that are simply DataContract internal classes to hold logging data.
DatabaseLoggerData
DatabaseLoggerDataParameter
 
I made a change to the DbContext class where I added three private properties with public getters/setters to hold the CompilerServices properties referenced above in the link. Within the DbContext I added a single constructor that takes those three values as parameters and assigns them to those three properties.
 
In the DatabaseLogFormatter code I changed the LogCommand, LogParameter, and LogResult methods to output the log info to my new types, then output it as JSON. This is an example of what a line of JSON log looks like (expanded for readability)…

``` json
{
"filePath":"E:\\dev\\AdventureWorksEFLogging",
"fileName":"Location.cs",
"memberName":"GetLocations",
"lineNumber":40,
"command":"SELECT \r\n    [Extent1].[LocationID] AS [LocationID], \r\n    [Extent1].[Name] AS [Name], \r\n    [Extent1].[CostRate] AS [CostRate], \r\n    [Extent1].[Availability] AS [Availability], \r\n    [Extent1].[ModifiedDate] AS [ModifiedDate]\r\n    FROM [Production].[Location] AS [Extent1]",
"parameters":
[
{
"name":"p__linq__0",
"value":"AdventureWorksEFLogging.AdventureWorksModel",
"dbType":"String"
}
],
"occurred":"1/17/2018 2:25:03 PM",
"elapsed":"6 milliseconds",
"exception":""
}
```

I also commented out the body of the Opened and Closed methods because with my logging it is not needed.
 
After much trial and error, that is the least changes to the base EF code that I could do to display this to the EF PG.
 
There will need to be changes to the code generator that creates the DbContext derived classes within customer code to implement those code generators to have a signature like this…

``` C#
public AdventureWorksModel([CallerFilePath] string filePath = null, [CallerMemberName] string memberName = null, [CallerLineNumber] int lineNumber = 0)
            : base("name=AdventureWorksModel", filePath, memberName, lineNumber)
        { }
```

This will also need the 
using System.Runtime.CompilerServices;
addition made so that those decorations can be used.
 
To turn this on, it uses the standard way of implementing the interception for EF:

``` xml
<interceptors>
                              <interceptor type="System.Data.Entity.Infrastructure.Interception.DatabaseLogger, EntityFramework">
                                         <parameters>
                                                   <parameter value="C:\Temp\LogOutput.txt"/>
                                         </parameters>
                               </interceptor>
                    </interceptors>

```

I did not do any work to show how to change the auto-code creation methodology. I have to believe this should be pretty easily done for the PG.

The code changes I made have been attached to this ticket. I also included the JSON output that the other app reads.

I would like to work with the PG to get these changes put in.

**Comment by divega** [comment]
Thanks @brebor for moving this discussion here. Notice I made some edits to make the code snippets more readable (I suggest you take a look at what I did for future reference). 

I think the usage information you showed me on email would also be relevant here, can you add it in either an edit to the original post or as a new comments? 

In principle if your proposal is to replace the existing constructors of `DbContext` with new constructors that caller info values is a non-starter for us, mainly for two reasons:

1. It would break binary compatibility
2. It would put a burden on all users (regardless of whether they care about this information) when they write their own derived `DbContext` (which effectively they always need to do). 

Adding this to some new constructor overloads seems better, but it is still not super compelling because:

1. You are relying on the proximity of the line of code that creates the context with the proximity of the line of code that trigger the actual database operations. This will not work well in the general case as the context can be constructed in one place and then passed down to a method that executes the queries or the SaveChanges calls in a completely different source code file.
2. As you already found, there are already existing constructors that take strings or no arguments and invoking the constructor without the arguments would be ambiguous. 
3. This wouldn't work well with modern patterns like dependency injection, since we the strings passed in the constructors cannot be services.

I mentioned on email that I could see use rather doing something like an extension method for `IQueryable<T>` (we could consider an overload of SaveChanges as well). The usage would look something like this:

``` csharp
var query = context.Products.Where(p => p.Name.StarthsWith(x)).WithCallerInformation();
```

This method woudl also have the same optional parameters you showed with the attributes so it would get the caller information from the compiler the same way.

This would allow finer granularity as the caller information would be included in the LINQ query that actually correlates with the SQL query, although it is not perfect because with LINQ you can declare a query once and then execute it many times. 

Another thing that is different about this method is that it would be an opt-in. If the user never calls the method then there is no infomration added on the log.

I see the fact that is "opt-in" as a feature, but I understand that you were after that would not require customers to change their code and recompile. I would argue that with your proposed approach you are not achieving that either:

Every customer would need to write a constructor on their derived `DbContext` before they can take advantage of this. 

Yet one more thing we could consider doing is to:

1. Add a "log info" string that you can set on the `DbContext` to cause it to be included in all subsequent log messages. 
2. Create `WithCallerInformation()` extension methods for `DbContext` and/or queries to simplify setting the log info to these values. 

This would enable the constructor pattern you mentioned as well as the query pattern I prefer.

**Comment by brebor** [comment]
Hi Brett, 

Good to hear from you. Thanks for this. 

Here are some comments on my first impressions on this, but can we you please instead create an issue on https://github.com/aspnet/entityframework6/issues/ so that all the discussion can happen there? 

1.	How is collecting execution context information in the constructor of the context going to help identify a specific query? Does this depend on the proximity between the call to the constructor and the execution of the query?
2.	From the question above, I am not clear on the constructor of the context being the right place to inject this information, but anyway, have you looked at the impact of adding these parameters as an option in addition to all the different constructors? 
3.	I would rather think an extension method on IQueryable<T> could be the way to go about something like this, e.g.:

```c#
var query = context.Products.Where(p => p.Name.StarthsWith(x)).WithCallerInformation();
```

This makes it opt-in (e.g. zero cost paid unless you want this in all your queries)
It could be useful for EF Core as well since it also has logging and tracing (it just uses different patterns for it)

Thanks,
Diego

To answer your questions…
For 1:
Basic call like this:
```c#
public static void GetDepartments()
{
	using (AdventureWorksModel model = new AdventureWorksModel())
	{
		List<Department> departments = model.Departments.ToList();
	}
}
```
Calls the constructor of AdventureWorksModel like this:
```c#
public AdventureWorksModel([CallerFilePath] string filePath = null, [CallerMemberName] string memberName = null, [CallerLineNumber] int lineNumber = 0)
           : base("name=AdventureWorksModel", filePath, memberName, lineNumber)
       { }
```
That calls the constructor passing the location of the instantiation of the DbContext in the calling code.
This is the code added to DbContext:
```c#
private string _compilerServicesFilePath;
public string CompilerServicesFilePath
{
    get { return _compilerServicesFilePath; }
    set { _compilerServicesFilePath = value; }
}
private string _compilerServicesMemberName;
public string CompilerServicesMemberName
{
    get { return _compilerServicesMemberName; }
    set { _compilerServicesMemberName = value; }
}
    private int _compilerServicesLineNumber;
public int CompilerServicesLineNumber
{
    get { return _compilerServicesLineNumber; }
    set { _compilerServicesLineNumber = value; }
}

/// <summary>
/// Constructs a new context instance using the given string as the name or connection string for the
/// database to which a connection will be made.
/// See the class remarks for how this is used to create a connection.
/// </summary>
/// <param name="nameOrConnectionString"> Either the database name or a connection string. </param>
[SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope")]
[SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
public DbContext(string nameOrConnectionString, string filePath, string memberName, int lineNumber)
{
            Check.NotEmpty(nameOrConnectionString, "nameOrConnectionString");
            InitializeLazyInternalContext(new LazyInternalConnection(this, nameOrConnectionString));
            CompilerServicesFilePath = filePath;
            CompilerServicesMemberName = memberName;
            CompilerServicesLineNumber = lineNumber;
}
```
So the DbContext has those three properties which are filled in via the constructor.

For 2:
I tried changing all the constructors to accept those params. The only one that wouldn’t work was the default constructor.
```c#
protected DbContext()
{
    InitializeLazyInternalContext(new LazyInternalConnection(this, GetType().DatabaseName()));
}
```
The problem is that those three parameters HAVE TO BE implemented as default parameters. So I was getting an ambiguous exception because the default constructor would look like this:
```c#
protected DbContext(string filePath, string memberName, int lineNumber)
{
    InitializeLazyInternalContext(new LazyInternalConnection(this, GetType().DatabaseName()));
}
```
Which is ambiguous with this one:
```c#
public DbContext(string nameOrConnectionString, string filePath, string memberName, int lineNumber)
{
    Check.NotEmpty(nameOrConnectionString, "nameOrConnectionString");

    InitializeLazyInternalContext(new LazyInternalConnection(this, nameOrConnectionString));

    CompilerServicesFilePath = filePath;
    CompilerServicesMemberName = memberName;
    CompilerServicesLineNumber = lineNumber;
}
```
Because those three params are default valued.

For 3:
I don’t understand how to implement this. Plus this would require the customer to implement different code. I am trying to write this so that customers do not need to change their code and recompile and republish.

They could simply add the interceptor code to their config file and then would start getting this in depth logging.

I am happy to change anything that you feel would be better implemented. Let me know how we can get this going!

Thanks again!
Brett

**Comment by brebor** [comment]
Hey Diego,

I understand your hesitance at replacing/overloading the constructors. We definitely do not want to have compatibility issues!

Extension methods are an interesting option however the problem with that approach is that it requires the customer to change their code, recompile and publish. Then to take the code out they have to reverse the process. From a supportability standpoint we cannot expect customers to change their code. We can ask that they turn logging on or off, which the interception pattern allows.

If we could develop an additional interceptor that could be turned on/off via the configuration file that would be an acceptable workaround. The problem I found with that is that the distance from the actual database calls caused the Caller information to not be accurate.

Perhaps a hybrid of extension methods and an additional interceptor could overcome this problem?

Your mention of “Add a "log info" string that you can set on the DbContext to cause it to be included in all subsequent log messages.”, has the problem of having to modify code.

You are correct in that going forward, with my proposed approaches, customers will have to download the newest version of EF and then recompile and publish to take advantage of the logging capabilities. This is a known problem and up to customers to evaluate the cost benefit analysis of implementing the newest version. However customers are already doing that with each new version of any software that comes out.

I will investigate a hybrid approach of extension methods with an interceptor. Please let me know what you think about that approach.

Brett

**Comment by divega** [comment]
Moving this out of the 6.3.0-preview5 milestone because we didn't do anything.
