### ISSUE TITLE
InsertOrUpdate functionality

### ISSUE THREAD

**Issue by bdebaere** [aspnet/EntityFramework6#456]
Would there be any drawback against using the code below for InsertOrUpdate functionality?

```csharp
        public virtual void InsertOrUpdate(Entity entity)
        {
            DbEntityEntry dbEntityEntry = _dbContext.Entry(entity);

            if (dbEntityEntry.State == EntityState.Detached)
            {
                _dbSet.Add(entity);
            }
            else
            {
                _dbSet.Attach(entity);
                dbEntityEntry.State = EntityState.Modified;
            }
        }
```

**Comment by ajcvickers** [comment]
@bdebaere On it's own the code above doesn't seem very useful to me, but it depends on how it is being used. Can you ask a more specific question?

**Comment by bdebaere** [comment]
@ajcvickers Well, I'm using it like below, avoiding having to write the lines which are common for both codepaths two times. Does this help?

```csharp
Entity entity = repository...;

if (entity == null)
{
    entity = new Entity
    {
        Name = "Bla"
    }
}
**entity.Quantity += 1;**

repository.InsertOrUpdate(entity);
```

**Comment by ajcvickers** [comment]
@bdebaere If the entity is in the Detached state, then calling Add will mark it as Added, and calling Attach will mark is as Unchanged. On its own this does not, to me, mean InsertOrUpdate. Changing Attach to Update makes more sense since the states will then be Added or Modified. However, if the state is not Detached, then it is already being tracked by the context, which likely means that both Attach and Update are not useful.

**Comment by bdebaere** [comment]
@ajcvickers I meant to include the state change to `EntityState.Modified`. I have updated my original post. It's working as intended. When the entity does not exist, it creates it, when it does, it performs an update.

My worry is that there might be an edge case that I didn't think of which will cause this to fail. What is your opinion on this?

**Comment by ajcvickers** [comment]
@bdebaere I can't give you a confident answer with just the code snippets posted.

**Comment by bdebaere** [comment]
@ajcvickers What do you need from me?

**Comment by ajcvickers** [comment]
@bdebaere None of the code posted so far makes very much sense to me. For example, why does the code Attach _and_ then set the state to Modified? Is the code querying? It seems that way because otherwise the detached check for new entities wouldn't make sense. But then, why attach at all? So if you post a much more complete code listing, then I might be able to make some concrete conclusions from it, but as it is since the code doesn't make much sense to me, I'm afraid it makes it very hard for me to say if it "works".
