### ISSUE TITLE
Inverse Property Hides Fluent Api Statement 

### ISSUE THREAD

**Issue by WarrenFerrell** [aspnet/EntityFramework6#478]
1. Create an Optional relationship

```C#
public class Student
{
	public int StudentId { get; set; }
	public string StudentName { get; set; }
}	

public class Skill
{
    public string Id { get; set; }
    public string Name { get; set; }
    
    public virtual Student Student { get; set; }
}

protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    modelBuilder.Entity<Skill>()
        .HasOptional<Student>(r => r.Student)
        .WithMany()
        .WillCascadeOnDelete(true);    
}
```

produces the following migration 
```C#
public override void Up()
{
    CreateTable(
        "dbo.Skills",
        c => new
            {
                Id = c.String(nullable: false, maxLength: 128),
                Name = c.String(),
                Student_StudentId = c.Int(),
            })
        .PrimaryKey(t => t.Id)
        .ForeignKey("dbo.Students", t => t.Student_StudentId, cascadeDelete: true) 
        // note cascadeDelete = true 
        .Index(t => t.Student_StudentId);
            
    CreateTable(
        "dbo.Students",
        c => new
            {
                StudentId = c.Int(nullable: false, identity: true),
                StudentName = c.String(),
            })
        .PrimaryKey(t => t.StudentId);
            
}

public override void Down()
{
    DropForeignKey("dbo.Skills", "Student_StudentId", "dbo.Students");
    DropIndex("dbo.Skills", new[] { "Student_StudentId" });
    DropTable("dbo.Students");
    DropTable("dbo.Skills");
}
```
2. Change Student to
```C#
public class Student
{
	public int StudentId { get; set; }
	public string StudentName { get; set; }

	[InverseProperty("Student")]
	public virtual ICollection<Skill> Skills { get; set; }
}
```
get the following migration 
```C#
public override void Up()
{
    DropForeignKey("dbo.Skills", "Student_StudentId", "dbo.Students");
    AddForeignKey("dbo.Skills", "Student_StudentId", "dbo.Students", "StudentId");
}
        
public override void Down()
{
    DropForeignKey("dbo.Skills", "Student_StudentId", "dbo.Students");
    AddForeignKey("dbo.Skills", "Student_StudentId", "dbo.Students", "StudentId", cascadeDelete: true);
}
```

The Fluent api cascadeDelete statement is hidden by the Inverse Property on Students. Add-Migration should throw an error that it cannot satisfy the CascadeDelete or try to reconcile the new navigation property on Student with the Fluent api statement. The behavior also occurs if you lump in the Student skills navigation property onto the first migration and if the relationship is one:one optional instead of many:one optional. Placing the InverseProperty on the Skill's Student navigation property creates the correct migration while not having any InverseProperty causes the migration to produce two separate foreign keys, one to satisfy the Fluent api and one for the navigation property on Student. Does not apply if the the relationship on Skill is HasRequired. Did not test but could probably be fixed by [having a CascadeDelete property](https://gist.github.com/tystol/20b07bd4e0043d43faff) on `ICollection<Skills>`.

**Comment by ajcvickers** [comment]
Adding some notes for triage after reading this. This code:
```C#
modelBuilder.Entity<Skill>()
        .HasOptional<Student>(r => r.Student)
        .WithMany()
        .WillCascadeOnDelete(true);    
```
says to create a uni-directional relationship with "Student" on one side and no navigation property on the other.

On the other hand, this:
```C#
[InverseProperty("Student")]
public virtual ICollection<Skill> Skills { get; set; }
```
says that the relationship should be bi-directional with Student on one side and Skills on the other.

This means that the relationship modeled with the data annotations is different than the one specified in the fluent API. In such a case, the on with the fluent API should win and the data annotation should be ignored, since fluent API should always take precedence over data annotations. Which in turn should mean that the relationship still gets cascade delete, so there does seem to be a bug here. 

However, the more interesting question is what happens to the "Skills" navigation property? if it didn't have Inverse on it, then it would be used to form a second relationship between the Skill and Student entity types. Should it still do that? Or is this a case where a data annotation must generate an error because there is no sensible way to resolve what the fluent API is saying with what the data annotations say?

**Comment by WarrenFerrell** [comment]
I think an error is the more appropriate response. The intention that leads to the mistake is trying to expose the Skill foreign key relationship on the Student class. This can be accomplished by placing the data annotation on the Skill entity. 

```C#
public class Skill
{
    public string Id { get; set; }
    public string Name { get; set; }
    
    [InverseProperty("Skills")]
    public virtual Student Student { get; set; }
}
```

An error is more informative and more likely to lead a user to this solution. Ignoring the DataAnnotation is a good way to generate an immense amount of confusion.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
