### ISSUE TITLE
Second level derived type is not in same type hierarchy as base type when intermediate type is ignored

### ISSUE THREAD

**Issue by justintconroy** [aspnet/EntityFramework6#480]
Assume you have 3 entity types. `BaseType`, `DerivedTypeA`, and `DerivedTypeB`. `DerivedTypeA` inherits from `BaseType` and `DerivedTypeB` inherits from `DerivedTypeA`. So:

```
DerivedTypeB->DerivedTypeA->BaseType
```

If you try to map `BaseType` and `DerivedTypeB`, but explicitly ignore `DerivedTypeA`, then EF no longer considers `BaseType` and `DerivedTypeB` to be part of the same hierarchy, and thus, Table Per Hierarchy mapping cannot be used. I don't know if this is a bug or if it's intended behavior. In most cases, this is actually fine because `DerivedTypeA` and `DerivedTypeB` have the same properties, so you don't really need to ignore `DerivedTypeA`. You can allow it to be mapped without any weirdness happening.

Where this doesn't work is when `DerivedTypeA` has a navigation property to another type that also inherits from a base type which is being explicitly ignored. At that point, you *must* ignore `DerivedTypeA`, or EF will map the foreign key to 2 different columns for `DerivedTypeA` and `DerivedTypeB` (this is because of #443), which is fairly undesirable behavior. However, if you ignore `DerivedTypeA`, and try to explicitly map `BaseType` and `DerivedTypeB` to the same table, you'll get the following exception when you try to generate a migration:

```
Unhandled Exception: System.InvalidOperationException: The entity types 'BaseType' and 'DerivedTypeB' cannot share table 'BaseTypes' because they are not in the same type hierarchy or do not have a valid one to one foreign key relationship with matching primary keys between them.
```

I've created a [test repo](https://github.com/justintconroy/TestEfTypeHierarchy) that demonstrates this and also provides a bit more explanation in the README about what I'm trying to do and why.

I believe that if #443 gets fixed, this will actually become a non-issue because the intermediate derived type won't need to be ignored anymore. So if that ticket gets fixed, I would more or less also consider this to be fixed, especially if it's actually intentional behavior.

**Comment by ajcvickers** [comment]
@justintconroy I'm not 100% sure if not mapping a type in the middle of a hierarchy is supported or not in the EF implementation of EDM. If it is, then this might be just a bug in Code First configuration that we can be fixed. If the issue goes deeper than that, then it's unlikely that it will be changed for EF6. Marking this as a bug for now.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
