### ISSUE TITLE
DbSet<T>.Find method behavior not correct on table inheritance

### ISSUE THREAD

**Issue by imzjy** [aspnet/EntityFramework6#510]
Let's say we have `Post` as storage table.
We have two of child classes: `NewsPost` and `AdPost`

When you want to get the `AdPost` but you pass it with ID of `NewsPost` you will get the exception of "Cannot cast Post_xxx to AdPost"

Except:
Just return null, due to ID is not `AdPost`. In further, the result should not depend on ID value if ID is not `AdPost`.

### Steps to reproduce
1. Create a table of Post
2. Create `Post class`, then `AdPost` and `NewsPost` that inheritance from `Post`
3. Create new `NewsPost` record, that have ID of 1.
4. Trying to filter with `var ad = context.AdPosts.Find(1)`

Except: 
`ad` equals `null`.

Real:
Cast exception.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by chrysikos** [comment]
Can you post the Model Configuration please?

**Comment by imzjy** [comment]
@chrysikos 
Thanks for the reply, the model configuration as following:

`    protected override void OnModelCreating(DbModelBuilder modelBuilder) {
      base.OnModelCreating(modelBuilder);

      modelBuilder.Properties()
        .Where(x => x.GetCustomAttributes(false).OfType<DecimalPrecisionAttribute>().Any())
        .Configure(c => {
          var attr = (DecimalPrecisionAttribute) c.ClrPropertyInfo
            .GetCustomAttributes(typeof(DecimalPrecisionAttribute), true).FirstOrDefault();
          c.HasPrecision(attr.Precision, attr.Scale);
        });
    }
`

**Comment by ajcvickers** [comment]
@imzjy This was something that was discussed in-depth at the time Find was implemented (many years ago) and arguments for both throwing and returning null were put forward. From what I remember the arguments for returning null were basically what you are saying. On the other hand, the arguments for throwing were along the lines of:
* Find should only be called with IDs that are valid for the entity type, and this is not a valid ID because it is being used for a different entity type.
* It's hard to not throw and have the result be consistent and expected across different types in the hierarchy. For example, what should happen if Find is called for:
  * A base type, but the entity found is of a derived type?
  * A derived type, but the entity found is of a base type?
  * The case you present where the types have a common base but one is not derived from the other?

Ultimately, the decision was made to throw in this case. I don't know if in retrospect that was the correct decision, but it is not something we are going to change going forward.

**Comment by imzjy** [comment]
@ajcvickers 
Thanks for let me know the more deeper thinking on how Find be implemented, and what's other cases should take consideration based on implementing the Find.
