### ISSUE TITLE
Performance degrades with LegacyCasModel="true"

### ISSUE THREAD

**Issue by TomLeeman** [aspnet/EntityFramework6#512]
A simple query to the Entity Framework continues to run slower with the following setting in the web.config of an ASP.NET application `<trust legacyCasModel="true" level="Full" />`

An example query is;
```
var query = context.Stocktakes
    .Include(s => s.Items)
    .Include(s => s.Items.Select(i => i.Product))
    .Where(s => s.StocktakeID == stocktakeID && s.SiteID == siteID)
    .AsNoTracking()
    .SingleOrDefault();
```

After restarting the app pool, the query runs in less than 1/4 of a second. Once there has been a small amount of traffic to the website, the performance begins to drop, taking around 6 seconds for the same query and so far taking up to 22 seconds for the same query after several hours of the application being hosted. The performance drop only seems to occur when changing legacyCasModel.

Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Windows Server 2008 R2

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
