### ISSUE TITLE
'INSERT' SQL statement with 'NULL' in parameters values.

### ISSUE THREAD

**Issue by osemyonov** [aspnet/EntityFramework6#520]
EF6 generates 'INSERT' sql statement with parameters for DbSet Entity:

```
INSERT [dbo].[Samples]([CreateDate], [GatewayId], [SensorId], [Value])
VALUES (@0, @1, @2, @3)

Information: 0 : -- @0: '4/12/2018 2:09:46 PM' (Type = DateTime2)
Information: 0 : -- @1: 'Test' (Type = AnsiString, Size = 16)
Information: 0 : -- @2: '0' (Type = Byte, Size = 1)
Information: 0 : -- @3: '0' (Type = Single)
```
as soon as Entity has one property (SensorId is nullable) value is NULL EF6 generates new sql statement:

```
INSERT [dbo].[Samples]([CreateDate], [GatewayId], [SensorId], [Value])
VALUES (@0, @1, NULL , @2)

Information: 0 : -- @0: '4/12/2018 3:08:40 PM' (Type = DateTime2)
Information: 0 : -- @1: 'Test' (Type = AnsiString, Size = 16)
Information: 0 : -- @2: '0' (Type = Single)
```
I need to use parameterized query (the same from sample 1) and pass DBNull.Value as a parameter's value.
Replacing value to NULL in VALUES (...) forces to create new execution plan in MS SQL server

Are there workarounds to fix it ?

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
IDE: Visual Studio 2017 15.6

**Comment by ajcvickers** [comment]
@divega Can you remember if this is expected behavior on EF6?

**Comment by Gluck1312** [comment]
Please, consider possibility to cache DbCommandDefinition of Insert and Delete for each store EntitySet. For Update command this is not possible - this command affects various combinations of changed columns.
Also, on execute multiple Insert/Delete commands, You may cache DbCommand instances for current batch, and, optionally, use DbCommand.Prepare().
This behavior may be controlled with some ObjectContext options or extended SaveOptions flags.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
