### ISSUE TITLE
IEnumerable.Contains no longer optimizes single-item case to =

### ISSUE THREAD

**Issue by damieng** [aspnet/EntityFramework6#521]
In EF 5 if you performed a Contains operation with just a single item it would perform = instead of IN so that the compiled query could be re-used.

The [DbInExpression change](https://github.com/aspnet/EntityFramework6/commit/a7b70f69e5518036b07699052d4ffc8afc1d83d4#diff-921b32a8c33660373ea20a77092b6af1) inadvertently broke this behavior.

### Steps to reproduce

```c#
var query = db.Simples.Where(e => new int[] { 1 }.Contains(e.Id)).ToString();
```

produces

```sql
SELECT
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Simples] AS [Extent1]
    WHERE [Extent1].[Id] IN (1)
```

Ideally it would produce

```sql
SELECT
    [Extent1].[Id] AS [Id]
    FROM [dbo].[Simples] AS [Extent1]
    WHERE [Extent1].[Id] = 1
```

### Further technical details
EF version: https://github.com/aspnet/EntityFramework6/commit/22a11d132306c257435fa7d6d75a31359cbbd05a
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6

**Comment by ajcvickers** [comment]
@damieng Move to EF Core?

**Comment by damieng** [comment]
Is this repo closed for PR's and new releases? 

Moving to core is non-trivial for us I suspect - is there a full feature comparison available?

**Comment by Seabizkit** [comment]
if you wanted the latter then why not write the latter i.e db.Simples.Where(x => x =1).ToString(); 
from what your wrote as linq the produced sql is what i would expect, otherwise it would not be predictable what the sql would be generated... if you want to make internal optimizations based of your scenario then use IQuerable and determine how many items there are, and then write code to adjust as you want.

**Comment by damieng** [comment]
@Seabizkit often apps have a filter list of some description that is fed into the Contains operator and many times that can be optimized to a single = operation which will take advantage of query plan caching as it is a single value.

Users of LINQ should not be expected to know intricate details about performance that the LINQ provider can easily do for them.  This worked automatically in earlier versions of EF and was likely just accidentally regressed with the DbInExpression work.

**Comment by Gluck1312** [comment]
Ideally, these cases may utilize table-valued parameters with SqlDbType.Structured.

**Comment by ErikEJ** [comment]
Unfortunately, TVPs requires the precense of pre-existing objects (table types) on the server

**Comment by Gluck1312** [comment]
Maybe, some EF mapping extensions may hints EF engine to using existings table types for Table-Valued parameters?

imagine:
dbModelBuilder.HasPrimitiveCollectionType<int>().WithDbTypeName("dbo.IntegerTable");

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
