### ISSUE TITLE
Missing support for EDM collections in DataRecordObjectView

### ISSUE THREAD

**Issue by denwanke** [aspnet/EntityFramework6#531]
Consider the following (artificial) code snippet:

```
var query = "SELECT customer.Name, (SELECT order.Date, order.Summary FROM customer.Orders as order) AS Orders FROM CustomerData.Customers AS customer";
var data = context.CreateQuery<object>(query).Execute(MergeOption.NoTracking);
```
When data gets data-bound in a hierarchical data-consuming component (from a third-party lib), the method `ITypedList.GetItemProperties()` returns no property descriptors for the nested (order) rows of a particular customer. 

In this case the parameter `listAccessors` contains the FieldDescriptor for the second field of the main data record but its real EDM type is nested in an EDM collection.

The following fix is suggested:
```
PropertyDescriptorCollection ITypedList.GetItemProperties(PropertyDescriptor[] listAccessors)
{
    if (listAccessors == null || listAccessors.Length == 0)
    {
        // Caller is requesting property descriptors for the root element type.
        return _propertyDescriptorsCache;
    }

    Type itemType = null;

    // Use the last PropertyDescriptor in the array to build the collection of returned property descriptors.
    var propertyDescriptor = listAccessors[listAccessors.Length - 1];
    var fieldDescriptor = propertyDescriptor as FieldDescriptor;
    if (fieldDescriptor != null && fieldDescriptor.EdmProperty != null)
    {
        var edmType = fieldDescriptor.EdmProperty.TypeUsage.EdmType;

        // Unwrap collection types
        if (edmType.BuiltInTypeKind == BuiltInTypeKind.CollectionType)
        {
            edmType = ((CollectionType)edmType).TypeUsage.EdmType;
        }

        // If the property descriptor describes a data record with the EDM type of RowType,
        // construct the collection of property descriptors from the property's EDM metadata.
        if (edmType.BuiltInTypeKind == BuiltInTypeKind.RowType)
        {
            // Retrieve property descriptors from EDM metadata.
            return MaterializedDataRecord.CreatePropertyDescriptorCollection((RowType)edmType, typeof(IDataRecord), true);
        }

        itemType = edmType.ClrType;
    }
            
    // Use the CLR type.

    if (itemType == null)
    {
        itemType = GetListItemType(propertyDescriptor.PropertyType);
    }

    return TypeDescriptor.GetProperties(itemType);
}
```
By the way, the call to `GetListItemType()` looks very suspicious (redundant) as the condition for FieldDecriptor seems actually be always fulfilled. Otherwise the implementation of `GetListItemType()` must be improved for handling at least `IEnumerable<T>`, given the fact the type can be obtained from a FieldDescriptor (see `FieldDescriptor.DetermineClrType()` for the reference).

**Comment by denwanke** [comment]
See also the issue #565.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
