### ISSUE TITLE
Add-Migration with slash in name produces unexpected results

### ISSUE THREAD

**Issue by SimonGustavsson** [aspnet/EntityFramework6#532]
Creating a migration with a trailing slash creates an unexpected(/invalid?) folder/file structure.

Noticed this when made a typo (I frequently switch between en-GB and en-US keyboard layouts).
Creating directories seem to be expected. But it looks to me like trailing slashes should be stripped from the migration name to prevent nameless files being created (I can't imagine anyone wanting that?).

### Steps to reproduce
Create a migration like this `Add-Migration Faulty\` Entity Framework will create the following structure:
```
\Migrations
    \201805071548165_Faulty
        .cs
        .designer.cs
```

Expected:
```
\Migrations
    201805071548165_Faulty.cs
    201805071548165_Faulty.designer.cs
```

### Further technical details
EF version: 6.2.0 (.NET 4.6.1)
Database Provider: EntityFramework.SqlServer
Operating system: e.g. Windows 10
IDE: Visual Studio 2017 15.6.7

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
