### ISSUE TITLE
Negated boolean filters are compiled to "<>" that prevents using indices in the DB

### ISSUE THREAD

**Issue by mesztam** [aspnet/EntityFramework6#562]
Hi,

if you write a query like this:
ctx.Messages.Where(q => !q.IsArchived)
then it is translated to this SQL query (~more-less):
Select ... FROM Messages WHERE IsArchived **<> 1**

The problem is the comparison like <> prevents the sql engine to use indicies including the IsArchived column. Better would be translating it to "IsArchived = 0".

(In this case, the IsArchive column has a large selectivity -> the big majority of the records is archived, so including this column in an index makes sense, )

The workaround is using q.IsArchived == false instead, but this is a bit ugly of course (and developers tend to forget it). Is there any chance to fix this in an upcoming version?

regards,
Tamas

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
