### ISSUE TITLE
Shouldn't automatically generated indexes for references in derived entities be filtered?

### ISSUE THREAD

**Issue by henrikdahl8240** [aspnet/EntityFramework6#569]
Let's assume we have the following simple case:
*) Entity AA derives from Entity A. We have the whole type hierarchy in one table.
*) Entity AA has a property BID being a foreign key for the ID column of Entity B.

Entity Framework will now make a non-clustered index for AA.BID which is perfectly reasonable, but shouldn't this index be filtered on the discriminator value for Entity AA so only rows in the table which denote instances of AA will make it to the index. As it is today, if another derived class of A, i.e. AB, will also have instances, null values (for BID, which is not a property of AB, but of AA) go to the index for each AB-row as the index is not filtered. So there will be plenty of useless performance-reducing null values in these automatically generated indexes.

Isn't that correct?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
