### ISSUE TITLE
Add intellisense to the code in the web browser so I can go to the definitions of stuff. 

### ISSUE THREAD

**Issue by mncourt** [aspnet/EntityFramework6#593]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by mncourt** [comment]
Can not see how dispose contains rollback or commit by clicking on the dispose method... no definiton.  I don't want to hunt around all day trying to find how or where you implement dispose.  Just want to click on it in Code in Github and go directly to the definition.  Sheesh.  You are M$ for crying out loud.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
