### ISSUE TITLE
too slow when executing first query

### ISSUE THREAD

**Issue by hiwjcn** [aspnet/EntityFramework6#60]
too slow when executing first query

**Comment by rowanmiller** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Closing as there is nothing actionable here.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html).
