### ISSUE TITLE
Can't create MetadataWorkspace for EntityTypeConfigurations which map to Views

### ISSUE THREAD

**Issue by CodeSchweinchen** [aspnet/EntityFramework6#600]
I'm trying to read Mappings (Fluent API)  from another project of mine by loading the assemblies and instantiating the :DbContext Types before using  ```c# ((IObjectContextAdapter)context).ObjectContext.MetadataWorkspace;```. Trying to call the Metadataworkspace however fails with an exception, whenever the "table" that I'm mapping to is a view: 

> EntityType 'SampleType1' has no key defined. Define the key for this EntityType.
> EntityType 'SampleType2' has no key defined. Define the key for this EntityType.
> EntitySet 'SampleSet1' is based on type 'SampleType1' that has no keys defined.
> EntitySet 'SampleSet2' is based on type 'SampleType1' that has no keys defined.
>at System.Data.Entity.Core.Metadata.Edm.EdmModel.Validate()
>at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
>at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
>at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
>at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
>at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
>at System.Data.Entity.Internal.InternalContext.Initialize()
>at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
>at > System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
>at Application.Domain.MappingsReader.GetMetadataFromContext(DbContext context) in > C:\PathToMyProject\MappingsReader.cs:line 66
>at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
>at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
>at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
>at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
 >at System.Linq.Parallel.SpoolingTaskBase.Work()

This happens with every Context that is mapped to a view, my contexts definetly have a primary key defined ( `HasKey(t => t.PrimaryKeyId);`). 

I realize that support for views is still spotty but it's weird that it doesn't work, although I guess it makes sense because as far as I can tell views can't have PKs in SqlServer anyways.

EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.5

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by CodeSchweinchen** [comment]
I'll write an example, because the project I'm using right now is proprietary code.

**Comment by CodeSchweinchen** [comment]
Wasn't able to reproduce in a smaller project, might be something wrong with our code. I'll test this more and reopen if I can reproduce it.
