### ISSUE TITLE
Setting comments on tables and columns (improvement)

### ISSUE THREAD

**Issue by pavlexander** [aspnet/EntityFramework6#604]
Currently it is impossible to add table comments using annotations or FluentAPI

### Current Workaround
Current workaround is to modifiy migration script like so:

``` C#
Sql("COMMENT ON TABLE \"TableName\" IS 'My table comment,'");
Sql("COMMENT ON COLUMN \"TableName\".ColumnName IS 'My column comment'");
```

I would appreciate to instead use annotations or Fluent API for this kind of functionality. This is not a bug but an improvement suggestion.

### Further technical details
EF version: 6.2.0
Database Provider: Oracle.ManagedDataAccess.EntityFramework
Operating system: Windows 10 x64
IDE: Visual Studio 2017 15.7.5 Pro

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
