### ISSUE TITLE
Can not Exclude Conputed column on insert/update

### ISSUE THREAD

**Issue by Kantuz001** [aspnet/EntityFramework6#605]
Hi, we have table in MS SQL
```
CREATE TABLE [dbo].[File2CreditRequest](
	[ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[ParentID] [int] NULL,
	[CRID] [int] NOT NULL,
	[Version] [int] NULL,
	[VersionGroupID]  AS (case [ParentID] when (0) then [ID] else [ParentID] end) PERSISTED NOT NULL,
 CONSTRAINT [PK_File2CREDITREQUEST] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[File2CreditRequest] ADD  CONSTRAINT [DF_File2CreditRequest_ParentID]  DEFAULT ((0)) FOR [ParentID]
GO

ALTER TABLE [dbo].[File2CreditRequest] ADD  CONSTRAINT [DF_File2CreditRequest_Version]  DEFAULT ((0)) FOR [Version]
GO

ALTER TABLE [dbo].[File2CreditRequest]  WITH CHECK ADD  CONSTRAINT [FK_File2CREDITREQUEST_VersionGroup] FOREIGN KEY([VersionGroupID])
REFERENCES [dbo].[File2CreditRequest] ([ID])
GO

ALTER TABLE [dbo].[File2CreditRequest] CHECK CONSTRAINT [FK_File2CREDITREQUEST_VersionGroup]
GO``
```
When i try to update this entity by EF i get error "InvalidOperationException: A dependent property in a ReferentialConstraint is mapped to a store-generated column. Column: 'VersionGroupID'".

So i tried to use [DatabaseGenerated(DatabaseGeneratedOption.Computed)] attribte, but the probled is that VersionGroupID column is computed and foreigh key the same time.
 
Any ideas?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
