### ISSUE TITLE
Support generic complex type mapping

### ISSUE THREAD

**Issue by mr-unicoder** [aspnet/EntityFramework6#624]
How can I map generic complex property?

Let's say I've a table with (Id int, Name nvarchar(50), Addresses nvarchar(max)) and I want to map this table to an entity like this:
```c#
public class Entity {
public int Id { get; set; }
public string Name { get; set; }
public JsonObject<List<Address>> Addresses { get; set; }
```

JsonObject<T> class is like this:
```c#
 public class JsonObject<T> where T : class
    {
        public JsonObject()
        {
        }

        public JsonObject(string jsonString)
        {
            JsonString = jsonString;
        }

        public JsonObject(T value)
        {
            Value = value;
        }

        public string JsonString
        {
            get
            {
                return JsonConvert.SerializeObject(Value);
            }
            set
            {
                Value = JsonConvert.DeserializeObject<T>(value);
            }
        }

        public T Value { get; set; }
    }
```
EF doesn't accept to map JsonObject<T> class.

I know the other way to map JSON fields by adding another string property to the entity itself and map it but this breaks the whole abstraction idea!
So, is there any way to make it work in the way I posted it?

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
