### ISSUE TITLE
Any good solution that has a better performance to loading data from non-leaf type by a TPT with one base entity having multiple subclass entities?

### ISSUE THREAD

**Issue by AlexSun98** [aspnet/EntityFramework6#634]
Our team is experiencing a TPT performance issue that eats a lot of CPU usage on DB server. It looks that EF can't be used in case you have large inheritance hierarchy. E.G. 9 types = 8 JOINs in any query to this hierarchy. If any query select leaf node in hierarchy, performance looks good. But when a query select a node/type having several subclasses, it creates big query with significant performance issues. With TPT, the number of union joins will be equivalent to number of derived entities. Is there any solution to optimize the inefficient query that created by EF6 when loading data from non-leaf type?

**Comment by AlexSun98** [comment]
I saw a lot of CASE WHEN & union statements in a 800-line SQL query that has been generated by EF. Some union joins are not necessary when discriminator Id doesn't exists.

**Comment by ajcvickers** [comment]
**EF Team Triage:** @AlexSun98 As far as I can remember, that's just the way EF6 generates queries for TPT mappings. This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
