### ISSUE TITLE
The debug-by-guessing experience for ThrowingMonitor error messages is not productive T.T

### ISSUE THREAD

**Issue by TimLovellSmith** [aspnet/EntityFramework6#646]
The problem with this error message is it is not very useful for debugging. You can see a previous operation is causing a problem because it wasn't 'completed', but you are given no clue *what* operation is causing the problem, which causes you to frantically code review huge chunks of code in search of a bug which could have instead been staring you in the face: imagine if instead it said something analogously specific to 'your previous operation SELECT TOP 10 FOO FROM BAR' was not completed, instead of the actual:

'A second operation started on this context before a previous asynchronous operation completed. Use 'await' to ensure that any asynchronous operations have completed before calling another method on this context. Any instance members are not guaranteed to be thread safe.
at System.Data.Entity.Internal.ThrowingMonitor.EnsureNotEntered()'

Reproduced with EF 6.1.1

**Comment by ajcvickers** [comment]
@TimLovellSmith This message usually indicates an architectural issue where the context is being used my multiple threads concurrently. It's not implemented in a way that an reliably detect all cases, or even to allow individual cases to be identified, but instead as a low-overhead way that has a good chance of catching concurrent use of the the context instance. Anything more would likely require actual locking, which is something we don't want to introduce because the context is specifically not thread-safe to avoid this overhead.

**Comment by TimLovellSmith** [comment]
>This message usually indicates an architectural issue where the context is being used my multiple threads concurrently

@ajcvickers ajcvikers BTW, what are the *unusual* cases? I couldn't see any of the usual suspects, like doing multiple queries with non-awaited Tasks, in this case.

**Comment by TimLovellSmith** [comment]
BTW #2: in case you are in a listening mood... the way I choose to perceive this issue is not an 'architectural issue', where it indicates that the app design is somehow poor, I instead perceive it as an unwanted side-effect of EF or leaky abstraction... although maybe you just meant to imply an architectural issue in general, and not specifically the app side...

I suppose if I really want to use it that way and not have to deal with this nonsense, I do have the option of trying to write a thread-safe wrapper for the context...

**Comment by ajcvickers** [comment]
@TimLovellSmith I'm saying it is by-design that context is not thread-safe, which means that architectures that assume it is thread-safe are flawed. For example, sharing a single context instance across multiple requests in a web app. So, usually, this isn't about finding the one place in the app where the context is being used in a non-thread-safe manner, but instead in recognizing that an architecture that does this is not okay. Unusually, there might be one place that is doing something different from how the context is normally used in the app, like spinning up a couple of threads and sharing an ad-hoc context instance.

**Comment by TimLovellSmith** [comment]
@ajcvickers My personal experience is that every time I have hit this error, the problem is usually not that the contexts are shared across multiple requests. Its nearly always, that we thought it was going to be OK to have some task parallelism within a single request.

**Comment by TimLovellSmith** [comment]
I also have always been suspicious that it might be possible we hit such an issue because of lazy enumeration somehow...

**Comment by TimLovellSmith** [comment]
Hmm... What if, whenever you detect this bug is occurring in an application, it turns on some additional diagnostics, that can capture the source (stack trace) of the unfinished asynchronous operations?

**Comment by jsteff** [comment]
Any ideas on how to do that ? I was looking into Crash monitoring tool in Azure app service but not sure if it will help since the exceptions are in hangfire jobs and it seems they are not _second chance exceptions_ but maybe I'm wrong. Also not sure when they will happen and maybe the Crash monitoring will be active for several days before catching anything meaningful.

**Comment by TimLovellSmith** [comment]
Sorry Jsteff, to clarify, I meant that more as a suggestion for the entity framework team... if they are still reading this thread!
