### ISSUE TITLE
Calling function in subquery causes exeption

### ISSUE THREAD

**Issue by iamimbohacker** [aspnet/EntityFramework6#650]
I have such function in my implementation of DbContext:

```
[TableValuedFunction(nameof(GetSomething), nameof(MyDbContext))]
public IQueryable<SomeData> GetSomething(int parameter)
{
        var userIdParameter = new ObjectParameter("UserId", parameter);
        return this.ObjectContext().CreateQuery<SomeData>($"[{nameof(GetSomething)}](@{userIdParameter.Name})", userIdParameter).AsQueryable();
}
```

I want to call that function in the subquery of another query:
```
var result = await context.Set<User>()
                .Select(e => new
                {
                    Item = e,
                    Something = context.GetSomething(e.UserId)
                })
                .ToListAsync();
```

But I get an exception:

Exception type: System.NotSupportedException. Message: LINQ to Entities does not recognize the method 'System.Linq.IQueryable`1[MyProject.Models.SomeData] GetSomething(Int32)' method, and this method cannot be translated into a store expression.. Extra details: []. Source: EntityFramework.

p.s:Am I able to call SQL function method inside projection?
I would like to create behaviour similar to CROSS APPLY under selection

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
