### ISSUE TITLE
Random 'System.Text.DecoderFallbackException

### ISSUE THREAD

**Issue by XVBob** [aspnet/EntityFramework6#662]
After building a WinForms application using EF 6.0 with database first I get the following errors randomly on the first start of the application. Most of the time a restart of the application solves the problem.

    'System.Text.DecoderFallbackException' in mscorlib.dll Die Bytes [E9] im Index 5974 können nicht von der angegebenen Codepage in Unicode übersetzt werden. (Bytes[E9] at index 5974 could not be translated from given codepage to Unicode)

    'System.Xml.XmlException' in System.Xml.dll Ungültiges Zeichen in der angegebenen Codierung. Zeile 5337, Position 50. (Invalid character in giving codepage.Row 5337, Position 50)

    'System.Data.Entity.Core.MetadataException' in EntityFramework.dll Schema specified is not valid. Errors: DataAccess.AppName.AppName.ssdl(5337,50) : error 0005: Ungültiges Zeichen in der angegebenen Codierung. Zeile 5337, Position 50. (Invalid character in giving codepage.Row 5337, Position 50)

It happens only but not always on the first start of the application. There seems to be no logic behind the error. I can do 20 builds without getting those exception and some days I just do one and the application shows those error Messages and has to be restarted because the metadata for EF is not loaded.

I checked the the AppName.ssdl file in the obj-Folder at the giving position:
`
<AssociationSet Name="FK_Folio_EST_Schaetzperioden" Association="Self.FK_Folio_EST_Schaetzperioden"> `

There is no unusual character in the line. Position 50 is an r.

The application is built on framework 4.51, x86, EF 6.1.3.

### Steps to reproduce
I am unable to reproduce the problem. There are is no obvious pattern when the problem occurs.

### Further technical details
EF version: 6.1.3
Database Provider: EntityFramework.SqlServer
Operating system:  Windows 10)
IDE: Visual Studio 2017 15.8.7

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by XVBob** [comment]
Hello,

I am aware that I have omitted the steps to reproduce the issue. My issue is that the behaviour is random and I have no idea what is happening. There are no steps to force this error from happening.

I submitted the issue in hope someone has come across this random error before. I think it might be an environmental issue.

With regards,

Robert

Von: Arthur Vickers <notifications@github.com>
Gesendet: Mittwoch, 14. November 2018 17:56
An: aspnet/EntityFramework6 <EntityFramework6@noreply.github.com>
Cc: Bakos, Robert (Extern) <Robert.Bakos@ruv.de>; Author <author@noreply.github.com>
Betreff: Re: [aspnet/EntityFramework6] Random 'System.Text.DecoderFallbackException (#662)


EF Team Triage: This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

Steps to reproduce

Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean 😄... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read Painless Bug Tracking<http://www.joelonsoftware.com/articles/fog0000000029.html>.

BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.
