### ISSUE TITLE
Update statements order with TPT

### ISSUE THREAD

**Issue by yohny** [aspnet/EntityFramework6#670]
This is not a bug per se, its more of an improvement request.

When having inherited model using TPT, inserting of such entity inserts first into base class table and afterwards into inherited class table (as there is FK relationship). This order is however not respected with update - when 2 properties on entity are updated (one originating in base class one in inherited class) the update statements are executed in inherited table first and afterwards in base table. 

This causes issues when there is for example trigger that validates some integrity check and it is hooked on inherited table - when such trigger fires one would expect that base table is updated already, but it is not the case currently.

### Steps to reproduce
example code is in this SO question: https://stackoverflow.com/questions/35210249/how-can-you-control-the-order-of-sql-updates-in-ef6-db-model-using-tpt-inheritan

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.3

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
