### ISSUE TITLE
It would seem that OnModelCreating is not virtual.

### ISSUE THREAD

**Issue by LJ9999** [aspnet/EntityFramework6#671]
This overengineered crap doesn't work. This doc says that OnModelCreating is virtual but it's not:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'MyMusicCollectionDBContext.OnModelCreating(ModelBuilder)': no suitable method found to override	TheGLJ	C:\Users\e5q8ngj\Documents\Projects\TheGLJ\TheGLJ\Models\MyMusicCollectionDBContext.cs	27	Active

	public class MyMusicCollectionDBContext : DbContext
	{
		// You can add custom code to this file. Changes will not be overwritten.
		// 
		// If you want Entity Framework to drop and regenerate your database
		// automatically whenever you change your model schema, please use data migrations.
		// For more information refer to the documentation:
		// http://msdn.microsoft.com/en-us/data/jj591621.aspx
	
		public MyMusicCollectionDBContext() : base("name=MyMusicCollectionDBContext")
		{
		}

		public System.Data.Entity.DbSet<TheGLJ.Models.GENRE> GENRE { get; set; }

		public System.Data.Entity.DbSet<TheGLJ.Models.ARTIST> ARTIST { get; set; }

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
			base.OnModelCreating(modelBuilder);
		}
	}

**Comment by CZEMacLeod** [comment]
@LJ9999 Firstly you could check yourself if the method is virtual - the source code is all here.
[https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/DbContext.cs#L227](https://github.com/aspnet/EntityFramework6/blob/c714ec0dfe87a14d929841bd543acd3fa802e786/src/EntityFramework/DbContext.cs#L227)
Secondly you will see that the parameter type is `DbModelBuilder`, not `ModelBuilder` which is why you are getting an error as the method signature you provided does not match the method you are trying to override.
I'm not sure where you took the example from, or if you have mistyped it.
VS will autocomplete the override for you with all the correct parameter types and name if you use it.
If there is a mistake in the official documentation/examples, please point out where it is.
There is an example of [fluent configuration](https://docs.microsoft.com/en-gb/ef/ef6/modeling/code-first/fluent/relationships) in the docs.
