### ISSUE TITLE
AssociationSetMapping with a compound key

### ISSUE THREAD

**Issue by dekenless** [aspnet/EntityFramework6#679]
According to the documentation [MSL Specification]( https://docs.microsoft.com/en-us/ef/ef6/modeling/designer/advanced/edmx/msl-spec), something like this should be possible:

```xml
 <AssociationSetMapping Name="FK_Course_Department"
                        TypeName="SchoolModel.FK_Course_Department"
                        StoreEntitySet="Course">
   <EndProperty Name="Department">
         <ScalarProperty Name="DepartmentID" ColumnName="DepartmentID" />
	 <ScalarProperty Name="PartitionID" ColumnName="PartitionID" />
   </EndProperty>
   <EndProperty Name="Course">
         <ScalarProperty Name="CourseID" ColumnName="CourseID" />
	 <ScalarProperty Name="PartitionID" ColumnName="PartitionID" />
   </EndProperty>
 </AssociationSetMapping>
```
Where the primary keys on Department and Course are DepartmentID+ParitionID and CourseID+PartitionID respectively.

However, if I do with it will yield an error 3021: Each of the following columns in table XXX is mapped to multiple conceptual side properties...

Is this not supported? And if not is there a way around this?

Thanks

**Comment by ajcvickers** [comment]
@dekenless A couple of things could be happening:
* The spec could be wrong.
* The spec could be right, but EF's implementation might not support something that is in the spec.
* Writing/understanding association set mappings by hand is not something I have ever really been able to do, so maybe something else needs to be in the mapping.

Regardless, it's very unlikely we will change any of the code around this in EF6.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
