### ISSUE TITLE
EF Designer assigning primary keys to models built from database views.

### ISSUE THREAD

**Issue by Manaswi-Upadhyaya** [aspnet/EntityFramework6#680]
**Issue Description**
In EF v6.2, a user having many items in his EDMX model adds another SQL view. However during import of the view into the model, it makes two of the columns as primary key columns. These PK columns happen to be the PKs of different tables.

When the code calls the view and returns resulting rows, if the two PK columns have the same values in them, the result set will duplicate the data for the rest of the columns instead of pulling the correct values.

We found some links that stated a workaround was to create a "dummy" column that would serve as the PK, however not sure if this is the best solution for the problem.

The problem is that when recreating a model from a database, it will revert to having the same schema.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by ericnewton76** [comment]
The dummy column workaround is only really needed if you need to do SaveChanges on the view I think. 

Can you post the query that’s being generated?  That might help with the duplicating items part of this issue

**Comment by ajcvickers** [comment]
@Manaswi-Upadhyaya Each entity type needs to have key properties defined that form a unique key for each entity instance. Reverse engineering of views is not good at doing this, so you'll often have to make manual changes to the model after creating it from the database.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
