### ISSUE TITLE
EF6 UseDatabaseNullSemantics = true has no effect on LINQ JOIN

### ISSUE THREAD

**Issue by bfmone** [aspnet/EntityFramework6#682]
Hi, 

I am using EF 6.2.0 and setting dbContext.Configuration.UseDatabaseNullSemantics = true; 
this does not affect the SQL produced by the JOIN operator :

SQL Output:
FROM      [dbo].[F_DETALHES] AS [Extent1]
    INNER JOIN [dbo].[FATURA] AS [Extent2] ON [Extent1].[Pk_factura] = [Extent2].[Pk]
    LEFT OUTER JOIN [dbo].[LINHAS_PARA_FATURAR] AS [Extent3] ON ([Extent3].[pk_cliente] IS NOT NULL) AND ([Extent1].[Pk] = [Extent3].[Pk_detalhe_factura_cliente]) AND (([Extent1].[pk_cliente] = [Extent3].[pk_cliente]) **OR (([Extent1].[pk_cliente] IS NULL) AND ([Extent3].[pk_cliente] IS NULL)**))

Query:
var query = (from detail in dbContext.F_DETALHES.AsNoTracking()
join invoice in dbContext.FATURA on detail.Pk_factura equals invoice.Pk
join cp in dbContext.LINHAS_PARA_FATURAR on new { pk = detail.Pk, cliente = detail.pk_cliente} equals new { pk = (Guid)cp.Pk_detalhe_factura_cliente, cliente = cp.pk_cliente} into cpAux
from cpLeftJoin in cpAux.DefaultIfEmpty()
...

pk_cliente is nullable<Guid> in each table

Found a similar bug in archive.codeplex.com but it still is not fixed.
the solution given in the codeplex bug was to move the join to the were clause, but I cant do that in case of left joins.

**Comment by bfmone** [comment]
Hi there
My context simplified:
```
 public partial class MyContext : DbContext
    {
        public MyContext(string connectionString)
            : base(connectionString) {
            ConfigureContext();
        }
     
        private void ConfigureContext()
        {
            Database.SetInitializer<MyContext>(null);

            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.UseDatabaseNullSemantics = true;
        }
   // ...
    }
```

And creation
```
using (MyContext dbContext = new MyContext(myConnectionString))
{
      //query
}
```

Actually the EF version I am using is 6.1.3 but I tried to update to 6.2.0 and tested but with the same results.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
