### ISSUE TITLE
FeatReq: BeforeUp AfterUp BeforeDown AfterDown partial methods in (generated migration name).designer.cs

### ISSUE THREAD

**Issue by ericnewton76** [aspnet/EntityFramework6#684]
Sometimes need a way to add script or unsupported migration stuff on before or after Up or Down... ie new partial methods BeforeUp AfterUp BeforeDown AfterDown

These partial methods can manually updated and be put into a separate file that won't get overwritten by `Add-migration -force` 

new (migrationname).Designer.cs:
```c#
		public override void Up()
		{
			BeforeUp();
                        MigrateUp(); //add-migration generated code
			AfterUp();
		}

		public override void Down()
		{
			BeforeDown();
                        MigrateDown(); //add-migration generated code
			AfterDown();
		}

		partial void BeforeUp();
		partial void MigrateUp();
		partial void AfterUp();
		partial void MigrateDown();
		partial void BeforeDown();
		partial void AfterDown(); 
```
this will work just fine going forward, since all the other Add-Migration code has been baked in already.  

And then Add-Migration writes out (migrationname).cs
```c#
public void MigrateUp()
{
    //migration statements
}
public void MigrateDown()
{
    //migration statements
}
```

Developer can now add (migrationname).manual.cs
```c#
public partial class (migrationTypeName)
{
	void AfterUp()
	{
		CreateStoredProcedure("sproc_name", "sproc body");
		CreateStoredProcedure("sproc_name2", "sproc body");

		ExecuteSql("UPDATE OldTableWithNewColumn SET NewColumn='some computed value' WHERE 1=1");
                //or if supporting multiple db backends, calls to other types to generate the appropriate sql
	}

	void BeforeDown()
	{
		DropStoredProcedure("sproc_name");
		DropStoredProcedure("sproc_name2");
	}

}
```

### Further technical details
EF version: 6.2.0+
Database Provider: all
Operating system: n/a
IDE: n/a

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
