### ISSUE TITLE
FeatReq: Add-Migration -force should have option or def behavior to reuse existing migrationid

### ISSUE THREAD

**Issue by ericnewton76** [aspnet/EntityFramework6#687]
Code first workflow, a developer evolving the database during coding realizes that the actual design needs to be tweaked a little

The Add-Migration -force should either reuse the migrationid for the given name or have an option to reuse it. 

I end up constantly having to rename the generated file names and migrationid so that my VCS can show me the changes from when I might’ve originally checked in that file and have the additional columns in the migration. 

Just a nice polishing touch I would call this. 

### Steps to reproduce

`Add-Migration -name asdf -force`

Or force reuse of migrationid:

`Add-Migration -name asdf -reuseid -force`

In either case, if the code fails to determine the existing id, then just warn that and generate with a new migrationId as like now

### Further technical details
EF version: featreq for post 6.2.0
Database Provider: n/a
Operating system: n/a 
IDE: n/a

**Comment by ericnewton76** [comment]
Ok strangely when i just ran `Add-Migration migrationname -force` it did reuse the migrationid.  So I'm seeing inconsistent behavior somehow.  I'll post back if I can reach a conclusion on this.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
