### ISSUE TITLE
Identity column change to None not applied

### ISSUE THREAD

**Issue by mafshin** [aspnet/EntityFramework6#69]
Is there any plan to support Identity change detection and generating the corresponding correct migration in `6.2` ?

Having an Identity column and then trying to turn off the identity insert with the following code has no effect in reality:

```
HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None)
```

In order to make this change applied, I had to comment all references to the entity including foreign key references and then create a migration to drop them, update the database, then uncomment all of the codes and references for the entity, set the `DatabaseGeneratedOption.None`, create a new migration, update the database. 
These set of operations in a complex model with many references and foreign keys is very messy.

[SO post](http://stackoverflow.com/questions/18907411/entering-keys-manually-with-entity-framework)

[RowMiler 2013 post](https://romiller.com/2013/04/30/ef6-switching-identity-onoff-with-a-custom-migration-operation/)

Version: EF 6.1.3
Tool: Visual Studio 2015 Update 3

**Comment by mafshin** [comment]
@rowanmiller, @divega   No idea to help me on this? I faced this issue yet again but this time I can't drop and recreate the table due to existing data.

**Comment by divega** [comment]
@mafshin We have no current plans to generate migration that rebuilds the schema for this case in EF6 (or in EF Core for that matter).

There is a question in StackOverflow about the SQL Server limitation: http://stackoverflow.com/questions/8230257/sql-server-remove-identity-from-a-column-in-a-table 

The most voted answer shows you can do it by adding a column to the table, copying the data there and then drop the original column, but even this option is hard if you have FKs depending on the column you need to remove the IDENTITY specification from, because you will have to disconnect them and connect them to the new column.
