### ISSUE TITLE
Performance issue: Imported SQL Stored procedure parameters of type CHAR(x) translate into 8000 characters at run-time

### ISSUE THREAD

**Issue by izmdev** [aspnet/EntityFramework6#709]
If a SQL Stored procedure is added into the EDMX model (aka Function import) and it contains one or more parameters of CHAR type, the EDMX model will not record any parameter size info. 

This causes EF6 to generate 8000-character space padded parameters at run-time ignoring the actual CHAR size. For instance, a CHAR(3) value of 'ABC' will be sent to SQL server as a string starting with ABC right-padded with 7997 spaces. This has negative impact on performance due to the increased query size and network traffic. Multiple CHAR parameters in an SP worsen the impact. 

### Steps to reproduce
Create a stored procedure similar to below:

```
CREATE PROCEDURE TestSP(@Param1 CHAR(3))
AS SELECT @Param1
```

1. Add this stored procedure to your EDMX model. 
2. Confirm no size attribute is recorded for parameter Param1:
```
<Function Name="TestSP" Aggregate="false" BuiltIn="false" NiladicFunction="false" IsComposable="false" ParameterTypeSemantics="AllowImplicitConversion" Schema="dbo">
          <Parameter Name="Param1" Type="char" Mode="In" />
</Function>
```
3. Generate corresponding C# code 
4. Create a test application to call generated SP code.
5. Run the test application and monitor the SP call using SQL Profiler.
6. Notice the 8000-character string representing Param1 (instead of 3 characters expected by the SP).
 
### Suggested resolution
Capture and store the MaxLength attribute (faucet) as part of the model for corresponding CHAR parameters. For instance, adding the MaxLength attribute to the model by hand resolves the issue:

`<Parameter Name="Param1" Type="char" Mode="In" MaxLength="3"  />
`

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
