### ISSUE TITLE
Better ReadOnly Entity Support

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#71]
_From @finite8 on September 25, 2016 22:57_

I have a lot of situations where i require that an entity must be read only. This includes things like Postcodes, Countries, Departments, Locations, etc. I need these mapped because i need to to queries and business logic based on them, but i need any attempt to make changes to these entities to be stopped. Obviously, it is a development issue if the application allows changes to such entities to be carried through, but if these issues are only detected after going live, it could be a costly mistake for an easily avoidable error.

My current workaround to get this behaviour is to do the following in my Entity Mapping Configuration (fluent)

```
MapToStoredProcedures(cfg => cfg
    .Insert(ccfg => ccfg.HasName("lolnope"))
    .Delete(ccfg => ccfg.HasName("lolnope"))
    .Update(ccfg => ccfg.HasName("lolnope")));
```

By giving it a stored procedure that doesn't exist, this prevents the entity either directly or indirectly (changing the entity when it is a child property on another entity) from ever having its changes being committed to the database. This seems to have the benefit of allowing me to be selective as well. For example, if i give it a false StoredProc for deletes, i can allow inserts and updates, but never a deletion.

Is it possible to get a Fluent Mapping option to prevent any combination of Insert, Update or Deletes on an entity, rather than my awfully hacky solution?

_Copied from original issue: aspnet/EntityFramework#6600_

**Comment by divega** [comment]
@finite8 I moved this issue to the EF6 repo because it seems to be a feature request for EF6, as we still don't have stored procedure mapping support for EF Core. 

Other than that...
- Your workaround seems very good to me. Preventing changes is one of the many ways you can leverage the ability to customize insert, update and delete operations in EF6. Of course, you could also have created an actual stored procedure that rasises an appropriate error.
- We currently don't have plans to create a new feature targeted specifically to the scenario you described in EF6. We haven't received a lot of feedback indicating that this is commonly needed. A more common situation, I suspect, is that certain entities (country, depertments, locations, product categories, etc.) are read only/reference data for the majority of use cases in an application but there still specific use cases in the application that are all about maintaining those entities up to date.

If you intended this to be a feature request for EF Core, I recommend that you make a comment on this issue: https://github.com/aspnet/EntityFramework/issues/245.

**Comment by finite8** [comment]
@divega 
I'm going to sound like a terrible person here, but i COMPLETELY forgot about EF Core!

I too like that i can customise how Insert, Deletes and Updates are done. I can live with it for now as the times that these kinds of errors would be raised are VERY rare and indicate a code error that needs to be resolved immediately. I would however prefer it to be rejected client side rather than have a intentionally malformed request hit the Server and let that raise the error, but that's just mainly an OCD / Perfectionist thing for me.

I am curious to know that as to what the normal pattern is when dealing with Globally Shared Entities (Departments, States, Locations, etc. Stuff that changes rarely. Can't think of a better name for it)? I know that the NHibernate solution would be to mark the entities as read only, and then cache them in the Second Level Cache and set up an expiry policy to expire them after a certain timeframe / SQL Server event / etc. This way, they are only ever loaded once and are shared by all Sessions / Contexts. Is this kind of feature something EF will have?

Thanks for getting back to me. Might create a stored proc to throw a nicer error so at least the exception is a bit more descriptive than "lolnope".

**Comment by divega** [comment]
>... mark the entities as read only, and then cache them in the Second Level Cache and set up an expiry policy to expire them after a certain timeframe ...

@finite8 I do see us enabling that kind of functionality in EF Core in the future (e.g. second level cache is tracked at https://github.com/aspnet/EntityFramework/issues/5858) , but it harder to imagine us bringing that size of a feature to the EF6 codebase. Moving forwards, you can expect our team to only fix bugs, implement small improvements and accept community contributions to the EF6.x code base.

FWIW, the way I have previously imagined this working is as set of policies that you can layer on top of/apply to a DbContext, as opposed to a fixed set of rules in the DbContext's model configuration. The reasoning is the same as I explained before: I believe the set of entities that are used as reference/shared/read-only data is not fixed by application but by use case within an application, while other details such as how entities are mapped to tables tend to be shared across all use cases within the same application.
