### ISSUE TITLE
Updating DB first Entity Model Digram Doesn't Generate the files

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#720]
From VS Feedback:

I'm using entity framework 6.2 with database first. I've tried this on webforms as well as class library projects.
When I'm updating the .edmx file, the new tables or columns in existing tables appear in the digram and the model browser but the code is missing. Whole new .cs files or new C# lines are not created.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by portTack** [comment]
I had same issue while using VS2019 preview. After updating from database, the DbContext and corresponding model class were not generated.

**Comment by BenCoden** [comment]
I am having a similar issue too. When I Update model from Database, I am adding an existing table, so I find my table in the db list check it and click add, but nothing happens, no error or message that I can see. 
I believe this is happening because my table does not have a primary key. That is the only difference I see between tables I have already add and this one. Is it a requirement for tables to have a primary key? If so is there a workaround?
My table in question is an audit table. I don't care for it to have an Id I only want to dump some data in it.

**Comment by ajcvickers** [comment]
Duplicate of #705
