### ISSUE TITLE
Multipart Index across Complex Types cannot be created

### ISSUE THREAD

**Issue by CZEMacLeod** [aspnet/EntityFramework6#721]
I have an entity with 2 (different) complex types as properties. I am trying to create a multipart index across 2 fields, 1 in each of the complex types.

```
modelBuilder.Entity(Of SEO.SEORecord).HasIndex(Function(sr) New With {sr.Device.IsSpider, sr.UserAgent.Family})
```
I get an exception to this
```
An exception of type 'System.InvalidOperationException' occurred in EntityFramework.dll but was not handled in user code
The properties expression 'sr => new VB$AnonymousType_18`2(IsSpider = sr.Device.IsSpider, Family = sr.UserAgent.Family)' is not valid. The expression should represent a property: C#: 't => t.MyProperty'  VB.Net: 'Function(t) t.MyProperty'. When specifying multiple properties use an anonymous type: C#: 't => new { t.MyProperty1, t.MyProperty2 }'  VB.Net: 'Function(t) New With { t.MyProperty1, t.MyProperty2 }'.
```

Using annotations I have individual indexes on each of the properties, but SQL Server tuning is showing that my queries are slowed down due to a missing multicolumn index.

There does not appear to be text overloads for HasIndex, so the only way I can complete this 'code first' is to manually create the index in a migration.

I assume this is a limitation of EF6, but wanted to check if there was a work-around I was not aware of.

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.0.0 Preview 3.0

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
