### ISSUE TITLE
SQL dependencies 208 error

### ISSUE THREAD

**Issue by 2006lixuan** [aspnet/EntityFramework6#727]
SQL dependencies 208 error throw occasionally but always throw since our web app deployed, there are 150 errors in last 30 days.
This error does not make request failed, it just need three or more times retry.
![208Error](https://user-images.githubusercontent.com/48664727/54505044-3b81b880-4971-11e9-9d5f-51691c56da2c.png)

And also got errors from DB logs as below
Invalid object name 'dbo.__MigrationHistory'.
Invalid object name 'dbo.EdmMetadata'.

I find a situation from stack overflow https://stackoverflow.com/questions/45842965/ms-application-insights-sql-dependencies-error-code-208

SDK
Microsoft.AspNetCore 2.0.1   EntityFramework 6.2.0

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is lacking enough information for us to be able to effectively triage it. In particular, it is missing the following information requested in the new issue template. Can you please provide this information?

> ### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

BTW we're not just doing this to be mean :smile:... we get a lot traffic on this project and it takes time to attempt to reproduce an issue based on fragments of information. In addition, our attempt is often unsuccessful as the exact conditions required to hit the issue are often not explicitly included in the code provided. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we ask that folks give us a self-contained way to reproduce an issue.

For a guide on submitting good bug reports, read [Painless Bug Tracking](http://www.joelonsoftware.com/articles/fog0000000029.html). 

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by 2006lixuan** [comment]
Thanks for your response, my project used code first EF but the database already exists(without table __MigrationHistory), what I want to do is  turn off the EF to detect table dbo.__MigrationHistory. I tried below code in my DbContext class but it not works, may I know what's wrong with below code?
![image](https://user-images.githubusercontent.com/48664727/54967625-e0744500-4fb2-11e9-9adf-d8a4f9f785a7.png)
![image](https://user-images.githubusercontent.com/48664727/54967643-f3871500-4fb2-11e9-9d85-08bc062b727f.png)

**Comment by ajcvickers** [comment]
@2006lixuan I'm sorry, but I don't understand what issue you are hitting or what the code shown is trying to do. If you are hitting what you think is a bug, then please post a runnable project/solution that demonstrates this so that we can fully investigate.

**Comment by 2006lixuan** [comment]
Add Database.SetInitializer(new NullDatabaseInitializer<LinkContext>()); in context OnModelCreating method fix this issue for me.
