### ISSUE TITLE
New feature Request Not an Issue: update from database project

### ISSUE THREAD

**Issue by CritStab** [aspnet/EntityFramework6#742]
This is a feature Request that I think would help everyone, I would like to see EF enable updates from a database project in my solution vs a database on the server. 

Exception message: NA
Stack trace: NA

### Steps to reproduce
Imagine opening VS and going into a solution. Inside that solution you have different types of projects for a web application. Project such as a console app, database project, and MVC web app (stay with me....). Imagine prior to working on the an issue you need to update the EF because other developers have recently moved database change to release. In the Database project you pull the latest changes. After which you go to the EF in the MVC app and update EF based on the DB project in the solution

C# : NA

### Further technical details
EF version: FUTURE
Database Provider: Database project in VS solution 
Operating system: Windows 10)
IDE: Visual Studio 2019

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
