### ISSUE TITLE
Checking for CreatedOn column in HistoryContext is always performed using 'dbo' schema

### ISSUE THREAD

**Issue by farlop** [aspnet/EntityFramework6#82]
My codefirst BD is deployed using a custom schema, so all my tables are [myschema].[tablename]. I'm logging an error on EF initialization where this query is performed:

    SELECT TOP (1) 
    [c].[CreatedOn] AS [CreatedOn]
    FROM [dbo].[__MigrationHistory] AS [c]

All others 'migrations' query are performed using correct schema name, for example:

    SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [myschema].[__MigrationHistory] AS [Extent1]
        WHERE [Extent1].[ContextKey] = @p__linq__0
    )  AS [GroupBy1]

 So it seems that something is missing in this query.

**Comment by rowanmiller** [comment]
This is by design, EF runs a bunch of different queries against the database to work out what state it is in - in this case, it's part of working out whether the database has an old version of the migrations history table. It catches the exceptions and swallows them, so you shouldn't see any failures at the app level.
