### ISSUE TITLE
Consider allowing an option for a "distributed" DbCompiledModel.

### ISSUE THREAD

**Issue by jthope** [aspnet/EntityFramework6#951]
We have two large DbContexts, one for tables (~400), and one for views (~500). These are code-first and mapped by using the System.Data.Entity.ModelConfiguration.EntityTypeConfiguration implementation. This is tucked into an assembly that is referenced by multiple service layers\front-ends.

Due to the size of the contexts, ~500MB of memory is required for each application, as they are in their own AppDomain. An example of each front-end/service that use EF:

- Web1 (WebForms) - ~500MB
- Web2 (Mvc) - ~500MB
- Services (Asmx) - ~500MB
- Services (WebApi) - ~500MB

The above applications run in the same "Website" in IIS. They all reference the same assembly that contains the EF configuration.

Ideally, it would be nice if all of the applications above could use a single reference to the information EF puts into the AppDomain cache. This could greatly reduce the memory required for solutions that contain several applications and use the same DbContext.

I have limited knowledge of cross AppDomain communication, so if this is something that is possible to do with EF in it's current state, any pointers would be helpful.

### Further technical details
EF version: 6.2
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: VS 2019

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
