### ISSUE TITLE
Entity framework IQueryable extension methods do not work with a sub query

### ISSUE THREAD

**Issue by LaurenceFrost** [aspnet/EntityFramework6#98]
I like to write my queries using extension methods where possible. So the following is a query which works for me. It gets all users that are Students.

```
var studentList = 
    (
        from u in db.Users
            .IsStudent()
        select u
    ).ToList();
```

Here is the definition of the IsStudent() extension method. It encapsulates the logic to determine if the user is a Student in a nice reusable method:

```
public static IQueryable<User> IsStudent(this IQueryable<User> u)
{
    return u.Where(x => x.Type == (int)UserTypes.Student);
}
```

Everything works beautifully until I try to use one of these extension methods in a sub-query. In the following query, I am attempting to get a list of all organisations which have at least 1 student:

```
IList<Organisations> orgList = (
   from o in db.Organisations
   where (
      from u in db.Users
         .IsStudent()
      where u.organisationId == o.Id
      select u
   ).Any()
   select o
);
```

However, this fails with the follwoing error:

> LINQ to Entities does not recognize the method 'System.Linq.IQueryable`1[MyProject.Domain.Models.User] IsStudent(System.Linq.IQueryable`1[MyProject.Domain.Models.User])' method, and this method cannot be translated into a store expression.

What am I doing wrong? Is there a reason that extension methods work at the top level, but not in a sub-query?

**Comment by LaurenceFrost** [comment]
I'm happy to create a VS2015 solution which re-creates this issue if that would help at all to diagnose the problem? Hopefully I have explained the problem well enough.

**Comment by divega** [comment]
@LaurenceFrost I am looking at this issue now. 

`IQueryable`-based LINQ implementations such as the one on EF6 work by parsing and translating query expression trees that represent calls to methods, access to properties and fields into some other format that can be executed elsewhere, e.g. on a database. In the particular case of EF, the attempt is made to translate all the expressions encountered in a query expression tree to SQL. If an expression is encountered that is not recognized, in most cases an exception is thrown.

The first (non-nested) case works because the code in the body of your method `IsStudent()` will be executed at query generation time and therefore the resulting query expression tree will not contain a call to `IsStudent()` but a call to `Where()`.

The second case in which the call is made in a nested expression will not invoke your method at query generation time but instead will result in an expression tree containing the call to your method. Since EF has no information on how to translate your method to SQL the query will fail at execution time.  

There are alternative patterns that I can recommend using as a workaround, e.g.:

1. Split query composition in multiple steps:
``` C#
var students = db.Users.IsStudent(); // this will build a query with a call to Where()
var organizations =
    from o in db.Organisations
    where (
        from u in students // students query referenced here
        where u.OrganizationId == o.Id
        select u).Any()
    select o;
```
2. Use methods returning expressions
``` C#
    public static class UserFilters
    {
        public static Expression<Func<User, bool>> IsStudent()
            => (user => user.Type == UserTypes.Student);
    }
...
// usage
var organizations =
    from o in db.Organisations
    where (
        from u in db.Users.Where(UserFilters.IsStudent())
        where u.OrganizationId == o.Id
        select u).Any()
    select o;
```

Note that latter pattern is supported thanks to a contribution by @brandondahler (see d9517e90117ec6104c52792cdc56f31088c34575 and bafa48e6987441e8b823e6970d44bb3996ea1934). We actually make an exception to the rule of throwing on methods we don't recognize if the method returns an expression of the right type. 

I am still thinking that your best choice would be to apply one of the workarounds but in the long term we could also recognize method calls on `IQueryable<T>` that return `IQueryable<T>` in a similar fashion to how we support methods that return expressions. 

cc @anpete @brandondahler in case they have some insights on supporting this on EF6 and EF Core.

**Comment by divega** [comment]
Clearing up milestone for triage. Investigation is done. I would like to chat about the possibility of supporting this pattern in either EF6 or EF Core (I don't think we have support for expression methods either currently in EF Core, but I haven't verified).

**Comment by LaurenceFrost** [comment]
Hi @divega,

Thanks very much for taking the time to investigate this for me. I really like the look of workaround number 1, so I'll give that a go now.

Cheers
Laurence
