### ISSUE TITLE
CRUD with dynamic table name

### ISSUE THREAD

**Issue by IlBaffo** [aspnet/EntityFramework6#991]
Hello,
Is there a way to CRUD different Tables (not known at build time) with the same Entity Class in CodeFirst (without migrations)?

Something like this (preudo-code):
```
using (var ctx = new MyContext())
{
    ctx.Set<MyEntity>("TableA").Add(new MyEntity{});
    ctx.Set<MyEntity>("TableB").Find(99);
}
```
or like this:
```
class MyContext {
    public Dictionary<string, DbSet<MyEntity>> DynamicEntities;
    void OnModelCreating(DbModelBuilder modelBuilder)
    {
        DynamicEntities.Add("TableA", Set<MyEntity>());
        DynamicEntities.Add("TableB", Set<MyEntity>());   
    }
}
using (var ctx = new MyContext())
{
    ctx.DynamicEntities["TableA"].Add(new MyEntity{});
    ctx.DynamicEntities["TableB"].Find(99);
}
```

If CRUD is impossible, would it be possible at least to have read only access (without tracking)?

Related Issues
https://github.com/aspnet/EntityFramework6/issues/386 **SqlQuery** was suggested it doesn't return an IQueryable, and composing the SQL is not an option for me.
https://github.com/aspnet/EntityFramework6/issues/497 Was closed because not reproducible

Thank you in advance.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Comment by IlBaffo** [comment]
So is this a yes or a no? I wasn't asking for an implementation.
Who could I ask this to?

**Comment by ajcvickers** [comment]
@IlBaffo You would have to build different models for each table, so essentially no.

**Comment by IlBaffo** [comment]
Ok, thank you, I'll look into other alternatives
